// Writes the Book of Tales for a village: node book.mjs [seed=1000] [years=300] [out=path] [perCentury=3]
// The village runs at the chronicle's pace with a time storm now and then (as the world kernel would send).
import { createVillage, run, YEAR } from "./village.mjs";
import { book } from "./tales.mjs";
import { writeFileSync } from "node:fs";
const seed = Number(process.argv[2] ?? 1000), years = Number(process.argv[3] ?? 300), perCentury = Number(process.argv[5] ?? 3);
const stormPlan = [];
for (let y = 50; y < years; y += 97) stormPlan.push({ day: y * YEAR + 20, household: (seed + y) % 6, days: 90 });
const NAMES = { 1000: "Wenbrook", 8919: "Harrowmere", 16838: "Ashcombe" };
const V = createVillage(seed, { stormPlan, name: NAMES[seed] ?? "Wenbrook" });
run(V, years * YEAR);
const b = book(V, years, perCentury);
const front = `---
title: "The Tales of ${V.name}, years 1-${years}"
created: 2026-09-29
type: generated
voice: agent-draft
author: generated by tools-src/studio/village-reference/book.mjs (seed ${seed}); sentence patterns by Claude (claude-opus-5-5)
status: a demonstration of the village simulation's range, not game text. Nothing here is decided until Enea says so
next_step: Enea and Hilmi read one book and say which tales feel like Unbound and which do not; that tunes the rules
---

`;
if (process.argv[4]) writeFileSync(process.argv[4], front + b.markdown + "\n");
console.log(b.markdown);
console.error(`${b.count} tales`);
