// Golden values for the GDScript port: the same seeds run here and there must give the same hashes at every
// checkpoint (the village state hash and the event-log hash). Writes the table as a GDScript file so it ships
// inside the game and the conformance runner can check on the phone too.
// Usage: node golden.mjs [outpath=../../../game/scripts/studio/village/sim/golden_data.gd]
import { writeFileSync } from "node:fs";
import { createVillage, stepDay, hashVillage, YEAR } from "./village.mjs";
import { key, strKey } from "./rng.mjs";
import * as C from "./content.mjs";

const out = process.argv[2] ?? "../../../game/scripts/studio/village/sim/golden_data.gd";
const CASES = [
  { seed: 1000, pace: 1, years: 10 },
  { seed: 8919, pace: 1, years: 10 },
  { seed: 16838, pace: C.LIVE_PACE, years: 10 },
];
const EVERY = 30; // days between checkpoints

// The stagings made since the last checkpoint, hashed (strings through strKey): the port's stagings must match too.
export function hashStagings(list) {
  let h = 2166136261;
  for (const st of list) {
    h = key(h, st.id); h = key(h, strKey(st.kind)); h = key(h, strKey(st.place)); h = key(h, st.start); h = key(h, st.end); h = key(h, strKey(st.outcome));
    for (const b of st.beats) { h = key(h, b.at); h = key(h, b.who); h = key(h, strKey(b.do)); h = key(h, b.slot); h = key(h, b.target); h = key(h, strKey(b.anim)); h = key(h, strKey(b.prop)); }
    for (const p of st.people) { h = key(h, p.id); h = key(h, p.outfit); }
  }
  return (h >>> 0).toString(16).padStart(8, "0");
}
const rows = [];
for (const c of CASES) {
  const V = createVillage(c.seed, { pace: c.pace });
  const checks = [];
  let lastStaging = -1;
  for (let d = 1; d <= c.years * YEAR; d++) {
    stepDay(V);
    if (d % EVERY === 0) {
      const fresh = V.stagings.filter((st) => st.id > lastStaging);
      if (fresh.length) lastStaging = fresh[fresh.length - 1].id;
      checks.push([V.day, hashVillage(V), (V.evHash >>> 0).toString(16).padStart(8, "0"), V.events.length, hashStagings(fresh), fresh.length]);
    }
  }
  rows.push({ ...c, checks, final: { people: V.people.length, events: V.events.length, crimes: V.crimes.length, cases: V.cases.length, stagings: V.stagingCount } });
  console.log(`seed ${c.seed} pace ${c.pace}: ${checks.length} checkpoints, final ${checks[checks.length - 1].join(" ")}`);
}
const gd = `# Generated by tools-src/studio/village-reference/golden.mjs - do not edit by hand.
# The JavaScript reference's hashes at checkpoints; the GDScript port must reproduce every one.
# Each check: [day, village hash, event-log hash, events so far, hash of the stagings made since the last
# check (golden.mjs hashStagings), how many].
extends RefCounted

const EVERY := ${EVERY}
const CASES := ${JSON.stringify(rows, null, "\t").replace(/"(\w+)":/g, '"$1":')}
`;
writeFileSync(out, gd);
console.log("wrote " + out);
