// Golden values for the GDScript port: the same seeds run here and there must give the same hashes at every
// checkpoint (the village state hash and the event-log hash). Writes the table as a GDScript file so it ships
// inside the game and the conformance runner can check on the phone too.
// Usage: node golden.mjs [outpath=../../../game/scripts/studio/village/sim/golden_data.gd]
import { writeFileSync } from "node:fs";
import { createVillage, stepDay, hashVillage, YEAR } from "./village.mjs";
import * as C from "./content.mjs";

const out = process.argv[2] ?? "../../../game/scripts/studio/village/sim/golden_data.gd";
const CASES = [
  { seed: 1000, pace: 1, years: 10 },
  { seed: 8919, pace: 1, years: 10 },
  { seed: 16838, pace: C.LIVE_PACE, years: 10 },
];
const EVERY = 30; // days between checkpoints
const rows = [];
for (const c of CASES) {
  const V = createVillage(c.seed, { pace: c.pace });
  const checks = [];
  for (let d = 1; d <= c.years * YEAR; d++) {
    stepDay(V);
    if (d % EVERY === 0) checks.push([V.day, hashVillage(V), (V.evHash >>> 0).toString(16).padStart(8, "0"), V.events.length]);
  }
  rows.push({ ...c, checks, final: { people: V.people.length, events: V.events.length, crimes: V.crimes.length, cases: V.cases.length, stagings: V.stagingCount } });
  console.log(`seed ${c.seed} pace ${c.pace}: ${checks.length} checkpoints, final ${checks[checks.length - 1].join(" ")}`);
}
const gd = `# Generated by tools-src/studio/village-reference/golden.mjs - do not edit by hand.
# The JavaScript reference's hashes at checkpoints; the GDScript port must reproduce every one.
extends RefCounted

const EVERY := ${EVERY}
const CASES := ${JSON.stringify(rows, null, "\t").replace(/"(\w+)":/g, '"$1":')}
`;
writeFileSync(out, gd);
console.log("wrote " + out);
