// Exports simulation-made stagings for the game's stage (game/scripts/studio/village/sim_stagings.gd): the
// first of each interesting kind and ending from a live-pace village, each with the story that led to it.
// Usage: node stagings.mjs [seed=16838] [years=30] [outpath]
import { writeFileSync } from "node:fs";
import { createVillage, stepDay, YEAR } from "./village.mjs";
import { storyOf } from "./tales.mjs";
import * as C from "./content.mjs";

const seed = Number(process.argv[2] ?? 16838), years = Number(process.argv[3] ?? 30);
const out = process.argv[4] ?? "../../../game/scripts/studio/village/sim_stagings.gd";
const WANT = [
  ["pillory", (st) => st.outcome === "carried_out" && st.beats.some((b) => b.prop === "stone")],
  ["pillory", (st) => st.outcome === "carried_out" && st.beats.some((b) => b.prop === "mud")],
  ["pillory", (st) => st.outcome === "crowd_turned"],
  ["bonfire", (st) => st.outcome === "carried_out"],
  ["hanging", (st) => st.outcome === "carried_out"],
  ["exile", () => true],
  ["trial", () => true],
  ["festival", () => true],
];
const V = createVillage(seed, { pace: C.LIVE_PACE });
const found = new Array(WANT.length).fill(null);
const seen = new Set();
for (let d = 0; d < years * YEAR && found.some((f) => !f); d++) {
  stepDay(V);
  for (const st of V.stagings) {
    if (seen.has(st.id)) continue;
    seen.add(st.id);
    const i = WANT.findIndex(([kind, ok], j) => !found[j] && st.kind === kind && ok(st));
    if (i < 0) continue;
    const ev = V.events.find((e) => e.type === "public_act" && e.data.staging === st.id);
    const story = ev ? storyOf(V, ev.id) : { title: st.kind, text: st.cue };
    found[i] = { ...st, title: story.title, story: story.text };
  }
}
const list = found.filter(Boolean);
for (const st of list) console.log(`${st.kind} ${st.outcome} day ${st.day}: ${st.beats.length} beats, ${st.people.length} people - ${st.title}`);
const gd = `# Generated by tools-src/studio/village-reference/stagings.mjs (seed ${seed}, live pace) - do not edit by hand.
# Stagings made by the village simulation, each with the story that led to it (staging.gd contract).
extends RefCounted

const STAGINGS := ${JSON.stringify(list, null, "\t")}
`;
writeFileSync(out, gd);
console.log("wrote " + out);
