// Exports simulation-made stagings for the game's stage (game/scripts/studio/village/sim_stagings.gd): the
// first of each interesting kind and ending from a live-pace village, each with the story that led to it.
// Usage: node stagings.mjs [seed=16838] [years=30] [outpath]
import { writeFileSync } from "node:fs";
import { createVillage, stepDay, YEAR } from "./village.mjs";
import { storyOf } from "./tales.mjs";
import * as C from "./content.mjs";

const seed = Number(process.argv[2] ?? 16838), years = Number(process.argv[3] ?? 60);
const out = process.argv[4] ?? "../../../game/scripts/studio/village/sim_stagings.gd";
const WANT = [
  ["pillory", (st) => st.outcome === "carried_out" && st.beats.some((b) => b.prop === "stone")],
  ["pillory", (st) => st.outcome === "carried_out" && st.beats.some((b) => b.prop === "mud")],
  ["pillory", (st) => st.outcome === "crowd_turned"],
  ["bonfire", (st) => st.outcome === "carried_out"],
  ["hanging", (st) => st.outcome === "carried_out"],
  ["exile", () => true],
  ["trial", () => true],
  ["festival", () => true],
  ["sacrifice", (st) => st.outcome === "carried_out"],
  ["sacrifice", (st) => st.outcome === "rescued"],
];
const found = new Array(WANT.length).fill(null);
// the first village that shows each wanted kind (the seed given first, then others), each with its seed
for (let tries = 0; tries < 8 && found.some((f) => !f); tries++) {
  const vs = seed + tries * 7919;
  // (a storm in the first year: the forebears and their rite are among what the stage must play)
  const V = createVillage(vs, { pace: C.LIVE_PACE, stormPlan: [{ day: 40, household: tries % 6, days: 90 }] });
  const seen = new Set();
  for (let d = 0; d < years * YEAR && found.some((f) => !f); d++) {
    stepDay(V);
    for (const st of V.stagings) {
      if (seen.has(st.id)) continue;
      seen.add(st.id);
      const i = WANT.findIndex(([kind, ok], j) => !found[j] && st.kind === kind && ok(st));
      if (i < 0) continue;
      const ev = V.events.find((e) => (e.type === "public_act" || e.type === "rite") && e.data.staging === st.id);
      const story = ev ? storyOf(V, ev.id) : { title: st.kind, text: st.cue };
      found[i] = { ...st, seed: vs, title: story.title, story: story.text };
    }
  }
}
const list = found.filter(Boolean);
for (const st of list) console.log(`${st.kind} ${st.outcome} day ${st.day}: ${st.beats.length} beats, ${st.people.length} people - ${st.title}`);
const gd = `# Generated by tools-src/studio/village-reference/stagings.mjs (live pace; each staging carries its seed) - do not edit by hand.
# Stagings made by the village simulation, each with the story that led to it (staging.gd contract).
extends RefCounted

const STAGINGS := ${JSON.stringify(list, null, "\t")}
`;
writeFileSync(out, gd);
console.log("wrote " + out);
