# Generated by tools-src/studio/village-reference/stagings.mjs (seed 16838, live pace) - do not edit by hand.
# Stagings made by the village simulation, each with the story that led to it (staging.gd contract).
extends RefCounted

const STAGINGS := [
	{
		"id": 104,
		"kind": "pillory",
		"place": "pillory",
		"start": 480,
		"end": 865,
		"phases": [
			{
				"name": "gather",
				"from": 480,
				"to": 540,
				"rescue": true
			},
			{
				"name": "pillory",
				"from": 540,
				"to": 830,
				"rescue": true
			},
			{
				"name": "end",
				"from": 830,
				"to": 865,
				"rescue": false
			}
		],
		"roles": {
			"victim": 29,
			"accuser": 8,
			"authority": 12,
			"crowd": [
				7,
				8,
				10,
				14,
				16,
				19,
				21,
				22,
				33,
				36,
				37,
				38,
				39,
				42,
				47,
				48,
				49,
				50,
				51,
				52
			]
		},
		"beats": [
			{
				"at": 480,
				"who": 12,
				"do": "walk_to",
				"slot": -1,
				"target": 29,
				"anim": "Walk_Formal",
				"prop": ""
			},
			{
				"at": 480,
				"who": 29,
				"do": "walk_to",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 485,
				"who": 7,
				"do": "walk_to",
				"slot": 0,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 486,
				"who": 8,
				"do": "walk_to",
				"slot": 1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 487,
				"who": 10,
				"do": "walk_to",
				"slot": 2,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 488,
				"who": 14,
				"do": "walk_to",
				"slot": 3,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 489,
				"who": 16,
				"do": "walk_to",
				"slot": 4,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 490,
				"who": 19,
				"do": "walk_to",
				"slot": 5,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 490,
				"who": 29,
				"do": "lock",
				"slot": -1,
				"target": -1,
				"anim": "Crouch_Idle",
				"prop": ""
			},
			{
				"at": 491,
				"who": 21,
				"do": "walk_to",
				"slot": 6,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 492,
				"who": 7,
				"do": "stand",
				"slot": 0,
				"target": -1,
				"anim": "Idle_No",
				"prop": ""
			},
			{
				"at": 492,
				"who": 22,
				"do": "walk_to",
				"slot": 7,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 493,
				"who": 8,
				"do": "stand",
				"slot": 1,
				"target": -1,
				"anim": "Idle_No",
				"prop": ""
			},
			{
				"at": 493,
				"who": 33,
				"do": "walk_to",
				"slot": 8,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 494,
				"who": 10,
				"do": "stand",
				"slot": 2,
				"target": -1,
				"anim": "Idle_No",
				"prop": ""
			},
			{
				"at": 494,
				"who": 36,
				"do": "walk_to",
				"slot": 9,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 495,
				"who": 37,
				"do": "walk_to",
				"slot": 10,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 496,
				"who": 16,
				"do": "stand",
				"slot": 4,
				"target": -1,
				"anim": "Idle_No",
				"prop": ""
			},
			{
				"at": 496,
				"who": 38,
				"do": "walk_to",
				"slot": 11,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 497,
				"who": 14,
				"do": "stand",
				"slot": 3,
				"target": -1,
				"anim": "Idle_Talking",
				"prop": ""
			},
			{
				"at": 497,
				"who": 19,
				"do": "stand",
				"slot": 5,
				"target": -1,
				"anim": "Idle_No",
				"prop": ""
			},
			{
				"at": 497,
				"who": 39,
				"do": "walk_to",
				"slot": 12,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 498,
				"who": 21,
				"do": "stand",
				"slot": 6,
				"target": -1,
				"anim": "Idle_No",
				"prop": ""
			},
			{
				"at": 498,
				"who": 42,
				"do": "walk_to",
				"slot": 13,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 499,
				"who": 47,
				"do": "walk_to",
				"slot": 14,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 500,
				"who": 48,
				"do": "walk_to",
				"slot": 15,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 501,
				"who": 49,
				"do": "walk_to",
				"slot": 16,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 502,
				"who": 37,
				"do": "stand",
				"slot": 10,
				"target": -1,
				"anim": "Idle_No",
				"prop": ""
			},
			{
				"at": 502,
				"who": 50,
				"do": "walk_to",
				"slot": 17,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 503,
				"who": 22,
				"do": "stand",
				"slot": 7,
				"target": -1,
				"anim": "Idle_No",
				"prop": ""
			},
			{
				"at": 503,
				"who": 38,
				"do": "stand",
				"slot": 11,
				"target": -1,
				"anim": "Idle_No",
				"prop": ""
			},
			{
				"at": 503,
				"who": 51,
				"do": "walk_to",
				"slot": 18,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 504,
				"who": 33,
				"do": "stand",
				"slot": 8,
				"target": -1,
				"anim": "Idle_No",
				"prop": ""
			},
			{
				"at": 504,
				"who": 52,
				"do": "walk_to",
				"slot": 19,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 505,
				"who": 36,
				"do": "stand",
				"slot": 9,
				"target": -1,
				"anim": "Idle_FoldArms",
				"prop": ""
			},
			{
				"at": 506,
				"who": 47,
				"do": "stand",
				"slot": 14,
				"target": -1,
				"anim": "Idle_No",
				"prop": ""
			},
			{
				"at": 507,
				"who": 48,
				"do": "stand",
				"slot": 15,
				"target": -1,
				"anim": "Idle_No",
				"prop": ""
			},
			{
				"at": 508,
				"who": 39,
				"do": "stand",
				"slot": 12,
				"target": -1,
				"anim": "Idle_No",
				"prop": ""
			},
			{
				"at": 509,
				"who": 42,
				"do": "stand",
				"slot": 13,
				"target": -1,
				"anim": "Idle_No",
				"prop": ""
			},
			{
				"at": 509,
				"who": 50,
				"do": "stand",
				"slot": 17,
				"target": -1,
				"anim": "Idle_No",
				"prop": ""
			},
			{
				"at": 512,
				"who": 49,
				"do": "stand",
				"slot": 16,
				"target": -1,
				"anim": "Idle_No",
				"prop": ""
			},
			{
				"at": 512,
				"who": 51,
				"do": "stand",
				"slot": 18,
				"target": -1,
				"anim": "Idle_Talking",
				"prop": ""
			},
			{
				"at": 513,
				"who": 52,
				"do": "stand",
				"slot": 19,
				"target": -1,
				"anim": "Idle_Talking",
				"prop": ""
			},
			{
				"at": 540,
				"who": 7,
				"do": "throw",
				"slot": 0,
				"target": 29,
				"anim": "OverhandThrow",
				"prop": "cabbage"
			},
			{
				"at": 541,
				"who": 29,
				"do": "react",
				"slot": -1,
				"target": 7,
				"anim": "Hit_Chest",
				"prop": ""
			},
			{
				"at": 547,
				"who": 8,
				"do": "throw",
				"slot": 1,
				"target": 29,
				"anim": "OverhandThrow",
				"prop": "turnip"
			},
			{
				"at": 548,
				"who": 29,
				"do": "react",
				"slot": -1,
				"target": 8,
				"anim": "Hit_Chest",
				"prop": ""
			},
			{
				"at": 554,
				"who": 10,
				"do": "throw",
				"slot": 2,
				"target": 29,
				"anim": "OverhandThrow",
				"prop": "cabbage"
			},
			{
				"at": 555,
				"who": 29,
				"do": "react",
				"slot": -1,
				"target": 10,
				"anim": "Hit_Chest",
				"prop": ""
			},
			{
				"at": 561,
				"who": 16,
				"do": "throw",
				"slot": 4,
				"target": 29,
				"anim": "OverhandThrow",
				"prop": "turnip"
			},
			{
				"at": 562,
				"who": 29,
				"do": "react",
				"slot": -1,
				"target": 16,
				"anim": "Hit_Chest",
				"prop": ""
			},
			{
				"at": 568,
				"who": 19,
				"do": "throw",
				"slot": 5,
				"target": 29,
				"anim": "OverhandThrow",
				"prop": "cabbage"
			},
			{
				"at": 569,
				"who": 29,
				"do": "react",
				"slot": -1,
				"target": 19,
				"anim": "Hit_Chest",
				"prop": ""
			},
			{
				"at": 575,
				"who": 21,
				"do": "throw",
				"slot": 6,
				"target": 29,
				"anim": "OverhandThrow",
				"prop": "turnip"
			},
			{
				"at": 576,
				"who": 29,
				"do": "react",
				"slot": -1,
				"target": 21,
				"anim": "Hit_Chest",
				"prop": ""
			},
			{
				"at": 630,
				"who": 7,
				"do": "throw",
				"slot": 0,
				"target": 29,
				"anim": "OverhandThrow",
				"prop": "mud"
			},
			{
				"at": 631,
				"who": 29,
				"do": "react",
				"slot": -1,
				"target": 7,
				"anim": "Hit_Chest",
				"prop": ""
			},
			{
				"at": 637,
				"who": 8,
				"do": "throw",
				"slot": 1,
				"target": 29,
				"anim": "OverhandThrow",
				"prop": "mud"
			},
			{
				"at": 638,
				"who": 29,
				"do": "react",
				"slot": -1,
				"target": 8,
				"anim": "Hit_Chest",
				"prop": ""
			},
			{
				"at": 644,
				"who": 10,
				"do": "throw",
				"slot": 2,
				"target": 29,
				"anim": "OverhandThrow",
				"prop": "mud"
			},
			{
				"at": 645,
				"who": 29,
				"do": "react",
				"slot": -1,
				"target": 10,
				"anim": "Hit_Chest",
				"prop": ""
			},
			{
				"at": 651,
				"who": 16,
				"do": "throw",
				"slot": 4,
				"target": 29,
				"anim": "OverhandThrow",
				"prop": "mud"
			},
			{
				"at": 652,
				"who": 29,
				"do": "react",
				"slot": -1,
				"target": 16,
				"anim": "Hit_Chest",
				"prop": ""
			},
			{
				"at": 658,
				"who": 19,
				"do": "throw",
				"slot": 5,
				"target": 29,
				"anim": "OverhandThrow",
				"prop": "mud"
			},
			{
				"at": 659,
				"who": 29,
				"do": "react",
				"slot": -1,
				"target": 19,
				"anim": "Hit_Chest",
				"prop": ""
			},
			{
				"at": 665,
				"who": 21,
				"do": "throw",
				"slot": 6,
				"target": 29,
				"anim": "OverhandThrow",
				"prop": "mud"
			},
			{
				"at": 666,
				"who": 29,
				"do": "react",
				"slot": -1,
				"target": 21,
				"anim": "Hit_Chest",
				"prop": ""
			},
			{
				"at": 672,
				"who": 22,
				"do": "throw",
				"slot": 7,
				"target": 29,
				"anim": "OverhandThrow",
				"prop": "mud"
			},
			{
				"at": 673,
				"who": 29,
				"do": "react",
				"slot": -1,
				"target": 22,
				"anim": "Hit_Chest",
				"prop": ""
			},
			{
				"at": 679,
				"who": 33,
				"do": "throw",
				"slot": 8,
				"target": 29,
				"anim": "OverhandThrow",
				"prop": "mud"
			},
			{
				"at": 680,
				"who": 29,
				"do": "react",
				"slot": -1,
				"target": 33,
				"anim": "Hit_Chest",
				"prop": ""
			},
			{
				"at": 830,
				"who": 12,
				"do": "release",
				"slot": -1,
				"target": 29,
				"anim": "Interact",
				"prop": ""
			},
			{
				"at": 835,
				"who": 29,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 840,
				"who": 7,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 841,
				"who": 8,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 842,
				"who": 10,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 843,
				"who": 14,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 844,
				"who": 16,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 845,
				"who": 19,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 846,
				"who": 21,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 847,
				"who": 22,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 848,
				"who": 33,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 849,
				"who": 36,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 850,
				"who": 37,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 851,
				"who": 38,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 852,
				"who": 39,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 853,
				"who": 42,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 854,
				"who": 47,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 855,
				"who": 48,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 856,
				"who": 49,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 857,
				"who": 50,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 858,
				"who": 51,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 859,
				"who": 52,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			}
		],
		"outcome": "carried_out",
		"cause": [
			"crime: a scuffle at the well",
			"accusation: Wat pointing at Rolf in the square"
		],
		"cue": "mud and jeers at Rolf in the pillory",
		"day": 1223,
		"people": [
			{
				"id": 29,
				"name": "Rolf",
				"outfit": 9,
				"home": "lodge",
				"role": "woodcutter",
				"marks": [
					"pilloried"
				]
			},
			{
				"id": 12,
				"name": "Garrow",
				"outfit": 0,
				"home": "round",
				"role": "elder",
				"marks": []
			},
			{
				"id": 16,
				"name": "Elsbet",
				"outfit": 9,
				"home": "cabin",
				"role": "priest",
				"marks": []
			},
			{
				"id": 7,
				"name": "Alys",
				"outfit": 11,
				"home": "cabin",
				"role": "farmer",
				"marks": []
			},
			{
				"id": 8,
				"name": "Wat",
				"outfit": 9,
				"home": "cabin",
				"role": "herder",
				"marks": []
			},
			{
				"id": 10,
				"name": "Oswin",
				"outfit": 12,
				"home": "cabin",
				"role": "herder",
				"marks": []
			},
			{
				"id": 14,
				"name": "Tilda",
				"outfit": 1,
				"home": "lodge",
				"role": "miller",
				"marks": []
			},
			{
				"id": 19,
				"name": "Bettony",
				"outfit": 11,
				"home": "hill",
				"role": "miller",
				"marks": []
			},
			{
				"id": 21,
				"name": "Cuthbert",
				"outfit": 10,
				"home": "hill",
				"role": "woodcutter",
				"marks": []
			},
			{
				"id": 22,
				"name": "Ilse",
				"outfit": 5,
				"home": "loaf",
				"role": "herder",
				"marks": []
			},
			{
				"id": 33,
				"name": "Ansel",
				"outfit": 6,
				"home": "loaf",
				"role": "farmer",
				"marks": []
			},
			{
				"id": 36,
				"name": "Wystan",
				"outfit": 2,
				"home": "loaf",
				"role": "woodcutter",
				"marks": []
			},
			{
				"id": 37,
				"name": "Godric",
				"outfit": 7,
				"home": "cabin",
				"role": "farmer",
				"marks": []
			},
			{
				"id": 38,
				"name": "Rose",
				"outfit": 9,
				"home": "cabin",
				"role": "herder",
				"marks": []
			},
			{
				"id": 39,
				"name": "Mara",
				"outfit": 1,
				"home": "loaf",
				"role": "farmer",
				"marks": []
			},
			{
				"id": 42,
				"name": "Gwen",
				"outfit": 5,
				"home": "loaf",
				"role": "farmer",
				"marks": []
			},
			{
				"id": 47,
				"name": "Edith",
				"outfit": 10,
				"home": "cabin",
				"role": "farmer",
				"marks": []
			},
			{
				"id": 48,
				"name": "Osric",
				"outfit": 10,
				"home": "hill",
				"role": "farmer",
				"marks": []
			},
			{
				"id": 49,
				"name": "Piers",
				"outfit": 9,
				"home": "loaf",
				"role": "child",
				"marks": []
			},
			{
				"id": 50,
				"name": "Hawise",
				"outfit": 6,
				"home": "hill",
				"role": "child",
				"marks": []
			},
			{
				"id": 51,
				"name": "Juliana",
				"outfit": 8,
				"home": "lodge",
				"role": "child",
				"marks": []
			},
			{
				"id": 52,
				"name": "Lettice",
				"outfit": 1,
				"home": "lodge",
				"role": "child",
				"marks": []
			}
		],
		"title": "Rolf in the Pillory",
		"story": "One evening old grudges came to blows: Rolf struck Wat. Wat named Rolf before the elder. Garrow, the elder, heard it in the square. The sentence was a day in the pillory. They pelted Rolf with mud in the pillory until dusk. They are remembered as Rolf of the Pillory."
	},
	{
		"id": 22,
		"kind": "bonfire",
		"place": "stake",
		"start": 720,
		"end": 1300,
		"phases": [
			{
				"name": "gather",
				"from": 720,
				"to": 780,
				"rescue": true
			},
			{
				"name": "bonfire",
				"from": 780,
				"to": 1250,
				"rescue": true
			},
			{
				"name": "end",
				"from": 1250,
				"to": 1300,
				"rescue": false
			}
		],
		"roles": {
			"victim": 0,
			"accuser": 6,
			"authority": 6,
			"crowd": [
				2,
				3,
				4,
				7,
				8,
				9,
				10,
				12,
				14,
				15,
				16,
				19,
				20,
				21,
				22,
				23,
				25,
				26,
				29,
				30,
				31,
				32,
				33,
				34,
				35,
				36,
				37,
				38,
				39,
				40,
				41,
				42,
				43,
				44,
				45
			]
		},
		"beats": [
			{
				"at": 720,
				"who": 0,
				"do": "walk_to",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 720,
				"who": 6,
				"do": "walk_to",
				"slot": -1,
				"target": 0,
				"anim": "Walk_Formal",
				"prop": ""
			},
			{
				"at": 725,
				"who": 2,
				"do": "walk_to",
				"slot": 0,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 726,
				"who": 3,
				"do": "walk_to",
				"slot": 1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 727,
				"who": 4,
				"do": "walk_to",
				"slot": 2,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 728,
				"who": 7,
				"do": "walk_to",
				"slot": 3,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 729,
				"who": 8,
				"do": "walk_to",
				"slot": 4,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 730,
				"who": 9,
				"do": "walk_to",
				"slot": 5,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 731,
				"who": 10,
				"do": "walk_to",
				"slot": 6,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 732,
				"who": 12,
				"do": "walk_to",
				"slot": 7,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 733,
				"who": 0,
				"do": "lock",
				"slot": -1,
				"target": -1,
				"anim": "Crouch_Idle",
				"prop": ""
			},
			{
				"at": 733,
				"who": 14,
				"do": "walk_to",
				"slot": 8,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 734,
				"who": 15,
				"do": "walk_to",
				"slot": 9,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 735,
				"who": 16,
				"do": "walk_to",
				"slot": 10,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 736,
				"who": 19,
				"do": "walk_to",
				"slot": 11,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 737,
				"who": 2,
				"do": "stand",
				"slot": 0,
				"target": -1,
				"anim": "Idle_FoldArms",
				"prop": ""
			},
			{
				"at": 737,
				"who": 20,
				"do": "walk_to",
				"slot": 12,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 738,
				"who": 21,
				"do": "walk_to",
				"slot": 13,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 739,
				"who": 4,
				"do": "stand",
				"slot": 2,
				"target": -1,
				"anim": "Idle_Talking",
				"prop": ""
			},
			{
				"at": 739,
				"who": 7,
				"do": "stand",
				"slot": 3,
				"target": -1,
				"anim": "Idle_No",
				"prop": ""
			},
			{
				"at": 739,
				"who": 22,
				"do": "walk_to",
				"slot": 14,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 740,
				"who": 8,
				"do": "stand",
				"slot": 4,
				"target": -1,
				"anim": "Idle_No",
				"prop": ""
			},
			{
				"at": 740,
				"who": 23,
				"do": "walk_to",
				"slot": 15,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 741,
				"who": 9,
				"do": "stand",
				"slot": 5,
				"target": -1,
				"anim": "Idle_No",
				"prop": ""
			},
			{
				"at": 741,
				"who": 25,
				"do": "walk_to",
				"slot": 16,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 742,
				"who": 10,
				"do": "stand",
				"slot": 6,
				"target": -1,
				"anim": "Idle_No",
				"prop": ""
			},
			{
				"at": 742,
				"who": 26,
				"do": "walk_to",
				"slot": 17,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 743,
				"who": 29,
				"do": "walk_to",
				"slot": 18,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 744,
				"who": 30,
				"do": "walk_to",
				"slot": 19,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 745,
				"who": 3,
				"do": "stand",
				"slot": 1,
				"target": -1,
				"anim": "Idle_Talking",
				"prop": ""
			},
			{
				"at": 745,
				"who": 31,
				"do": "walk_to",
				"slot": 20,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 746,
				"who": 32,
				"do": "walk_to",
				"slot": 21,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 747,
				"who": 33,
				"do": "walk_to",
				"slot": 22,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 748,
				"who": 15,
				"do": "stand",
				"slot": 9,
				"target": -1,
				"anim": "Idle_No",
				"prop": ""
			},
			{
				"at": 748,
				"who": 34,
				"do": "walk_to",
				"slot": 23,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 749,
				"who": 12,
				"do": "stand",
				"slot": 7,
				"target": -1,
				"anim": "Idle_No",
				"prop": ""
			},
			{
				"at": 749,
				"who": 35,
				"do": "walk_to",
				"slot": 24,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 750,
				"who": 14,
				"do": "stand",
				"slot": 8,
				"target": -1,
				"anim": "Idle_No",
				"prop": ""
			},
			{
				"at": 750,
				"who": 19,
				"do": "stand",
				"slot": 11,
				"target": -1,
				"anim": "Idle_No",
				"prop": ""
			},
			{
				"at": 750,
				"who": 36,
				"do": "walk_to",
				"slot": 25,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 751,
				"who": 20,
				"do": "stand",
				"slot": 12,
				"target": -1,
				"anim": "Idle_No",
				"prop": ""
			},
			{
				"at": 751,
				"who": 37,
				"do": "walk_to",
				"slot": 26,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 752,
				"who": 16,
				"do": "stand",
				"slot": 10,
				"target": -1,
				"anim": "Idle_No",
				"prop": ""
			},
			{
				"at": 752,
				"who": 21,
				"do": "stand",
				"slot": 13,
				"target": -1,
				"anim": "Idle_No",
				"prop": ""
			},
			{
				"at": 752,
				"who": 38,
				"do": "walk_to",
				"slot": 27,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 753,
				"who": 22,
				"do": "stand",
				"slot": 14,
				"target": -1,
				"anim": "Idle_No",
				"prop": ""
			},
			{
				"at": 753,
				"who": 39,
				"do": "walk_to",
				"slot": 28,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 754,
				"who": 23,
				"do": "stand",
				"slot": 15,
				"target": -1,
				"anim": "Idle_No",
				"prop": ""
			},
			{
				"at": 754,
				"who": 40,
				"do": "walk_to",
				"slot": 29,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 755,
				"who": 30,
				"do": "stand",
				"slot": 19,
				"target": -1,
				"anim": "Idle_No",
				"prop": ""
			},
			{
				"at": 755,
				"who": 41,
				"do": "walk_to",
				"slot": 30,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 756,
				"who": 31,
				"do": "stand",
				"slot": 20,
				"target": -1,
				"anim": "Idle_No",
				"prop": ""
			},
			{
				"at": 756,
				"who": 42,
				"do": "walk_to",
				"slot": 31,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 757,
				"who": 32,
				"do": "stand",
				"slot": 21,
				"target": -1,
				"anim": "Idle_FoldArms",
				"prop": ""
			},
			{
				"at": 757,
				"who": 43,
				"do": "walk_to",
				"slot": 32,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 758,
				"who": 33,
				"do": "stand",
				"slot": 22,
				"target": -1,
				"anim": "Idle_No",
				"prop": ""
			},
			{
				"at": 758,
				"who": 44,
				"do": "walk_to",
				"slot": 33,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 759,
				"who": 45,
				"do": "walk_to",
				"slot": 34,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 760,
				"who": 2,
				"do": "carry",
				"slot": 0,
				"target": -1,
				"anim": "Walk_Carry",
				"prop": "wood"
			},
			{
				"at": 760,
				"who": 25,
				"do": "stand",
				"slot": 16,
				"target": -1,
				"anim": "Idle_FoldArms",
				"prop": ""
			},
			{
				"at": 760,
				"who": 34,
				"do": "stand",
				"slot": 23,
				"target": -1,
				"anim": "Idle_FoldArms",
				"prop": ""
			},
			{
				"at": 761,
				"who": 26,
				"do": "stand",
				"slot": 17,
				"target": -1,
				"anim": "Idle_No",
				"prop": ""
			},
			{
				"at": 761,
				"who": 36,
				"do": "stand",
				"slot": 25,
				"target": -1,
				"anim": "Idle_No",
				"prop": ""
			},
			{
				"at": 762,
				"who": 29,
				"do": "stand",
				"slot": 18,
				"target": -1,
				"anim": "Idle_No",
				"prop": ""
			},
			{
				"at": 762,
				"who": 37,
				"do": "stand",
				"slot": 26,
				"target": -1,
				"anim": "Idle_No",
				"prop": ""
			},
			{
				"at": 763,
				"who": 38,
				"do": "stand",
				"slot": 27,
				"target": -1,
				"anim": "Idle_No",
				"prop": ""
			},
			{
				"at": 766,
				"who": 35,
				"do": "stand",
				"slot": 24,
				"target": -1,
				"anim": "Idle_No",
				"prop": ""
			},
			{
				"at": 767,
				"who": 39,
				"do": "stand",
				"slot": 28,
				"target": -1,
				"anim": "Idle_No",
				"prop": ""
			},
			{
				"at": 767,
				"who": 41,
				"do": "stand",
				"slot": 30,
				"target": -1,
				"anim": "Idle_FoldArms",
				"prop": ""
			},
			{
				"at": 767,
				"who": 42,
				"do": "stand",
				"slot": 31,
				"target": -1,
				"anim": "Idle_No",
				"prop": ""
			},
			{
				"at": 768,
				"who": 43,
				"do": "stand",
				"slot": 32,
				"target": -1,
				"anim": "Idle_No",
				"prop": ""
			},
			{
				"at": 769,
				"who": 44,
				"do": "stand",
				"slot": 33,
				"target": -1,
				"anim": "Idle_No",
				"prop": ""
			},
			{
				"at": 770,
				"who": 45,
				"do": "stand",
				"slot": 34,
				"target": -1,
				"anim": "Idle_No",
				"prop": ""
			},
			{
				"at": 773,
				"who": 40,
				"do": "stand",
				"slot": 29,
				"target": -1,
				"anim": "Idle_No",
				"prop": ""
			},
			{
				"at": 780,
				"who": 3,
				"do": "carry",
				"slot": 1,
				"target": -1,
				"anim": "Walk_Carry",
				"prop": "wood"
			},
			{
				"at": 780,
				"who": 7,
				"do": "throw",
				"slot": 3,
				"target": 0,
				"anim": "OverhandThrow",
				"prop": "cabbage"
			},
			{
				"at": 780,
				"who": 12,
				"do": "gesture",
				"slot": -1,
				"target": -1,
				"anim": "Spell_Simple_Idle",
				"prop": ""
			},
			{
				"at": 781,
				"who": 0,
				"do": "react",
				"slot": -1,
				"target": 7,
				"anim": "Hit_Chest",
				"prop": ""
			},
			{
				"at": 787,
				"who": 10,
				"do": "throw",
				"slot": 6,
				"target": 0,
				"anim": "OverhandThrow",
				"prop": "turnip"
			},
			{
				"at": 788,
				"who": 0,
				"do": "react",
				"slot": -1,
				"target": 10,
				"anim": "Hit_Chest",
				"prop": ""
			},
			{
				"at": 794,
				"who": 12,
				"do": "throw",
				"slot": 7,
				"target": 0,
				"anim": "OverhandThrow",
				"prop": "cabbage"
			},
			{
				"at": 795,
				"who": 0,
				"do": "react",
				"slot": -1,
				"target": 12,
				"anim": "Hit_Chest",
				"prop": ""
			},
			{
				"at": 800,
				"who": 4,
				"do": "carry",
				"slot": 2,
				"target": -1,
				"anim": "Walk_Carry",
				"prop": "wood"
			},
			{
				"at": 801,
				"who": 15,
				"do": "throw",
				"slot": 9,
				"target": 0,
				"anim": "OverhandThrow",
				"prop": "turnip"
			},
			{
				"at": 802,
				"who": 0,
				"do": "react",
				"slot": -1,
				"target": 15,
				"anim": "Hit_Chest",
				"prop": ""
			},
			{
				"at": 808,
				"who": 16,
				"do": "throw",
				"slot": 10,
				"target": 0,
				"anim": "OverhandThrow",
				"prop": "cabbage"
			},
			{
				"at": 809,
				"who": 0,
				"do": "react",
				"slot": -1,
				"target": 16,
				"anim": "Hit_Chest",
				"prop": ""
			},
			{
				"at": 815,
				"who": 19,
				"do": "throw",
				"slot": 11,
				"target": 0,
				"anim": "OverhandThrow",
				"prop": "turnip"
			},
			{
				"at": 816,
				"who": 0,
				"do": "react",
				"slot": -1,
				"target": 19,
				"anim": "Hit_Chest",
				"prop": ""
			},
			{
				"at": 820,
				"who": 7,
				"do": "carry",
				"slot": 3,
				"target": -1,
				"anim": "Walk_Carry",
				"prop": "wood"
			},
			{
				"at": 1200,
				"who": 2,
				"do": "stand",
				"slot": 0,
				"target": -1,
				"anim": "Idle_Torch",
				"prop": "torch"
			},
			{
				"at": 1201,
				"who": 3,
				"do": "stand",
				"slot": 1,
				"target": -1,
				"anim": "Idle_Torch",
				"prop": "torch"
			},
			{
				"at": 1202,
				"who": 4,
				"do": "stand",
				"slot": 2,
				"target": -1,
				"anim": "Idle_Torch",
				"prop": "torch"
			},
			{
				"at": 1250,
				"who": 0,
				"do": "fall",
				"slot": -1,
				"target": -1,
				"anim": "Death01",
				"prop": ""
			},
			{
				"at": 1260,
				"who": 2,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 1261,
				"who": 3,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 1262,
				"who": 4,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 1263,
				"who": 7,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 1264,
				"who": 8,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 1265,
				"who": 9,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 1266,
				"who": 10,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 1267,
				"who": 12,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 1268,
				"who": 14,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 1269,
				"who": 15,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 1270,
				"who": 16,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 1271,
				"who": 19,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 1272,
				"who": 20,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 1273,
				"who": 21,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 1274,
				"who": 22,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 1275,
				"who": 23,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 1276,
				"who": 25,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 1277,
				"who": 26,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 1278,
				"who": 29,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 1279,
				"who": 30,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 1280,
				"who": 31,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 1281,
				"who": 32,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 1282,
				"who": 33,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 1283,
				"who": 34,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 1284,
				"who": 35,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 1285,
				"who": 36,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 1286,
				"who": 37,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 1287,
				"who": 38,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 1288,
				"who": 39,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 1289,
				"who": 40,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 1290,
				"who": 41,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 1291,
				"who": 42,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 1292,
				"who": 43,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 1293,
				"who": 44,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 1294,
				"who": 45,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			}
		],
		"outcome": "carried_out",
		"cause": [
			"crime: charms of twisted straw found by a doorway",
			"accusation: Tobin pointing at Osric in the square"
		],
		"cue": "wood piled round the stake",
		"day": 205,
		"people": [
			{
				"id": 0,
				"name": "Osric",
				"outfit": 1,
				"home": "cottage",
				"role": "farmer",
				"marks": []
			},
			{
				"id": 6,
				"name": "Tobin",
				"outfit": 8,
				"home": "cabin",
				"role": "elder",
				"marks": []
			},
			{
				"id": 12,
				"name": "Garrow",
				"outfit": 0,
				"home": "round",
				"role": "priest",
				"marks": []
			},
			{
				"id": 2,
				"name": "Dunstan",
				"outfit": 11,
				"home": "cottage",
				"role": "child",
				"marks": []
			},
			{
				"id": 3,
				"name": "Agnes",
				"outfit": 12,
				"home": "lodge",
				"role": "smith",
				"marks": []
			},
			{
				"id": 4,
				"name": "Edric",
				"outfit": 5,
				"home": "cottage",
				"role": "child",
				"marks": []
			},
			{
				"id": 7,
				"name": "Alys",
				"outfit": 11,
				"home": "cabin",
				"role": "farmer",
				"marks": []
			},
			{
				"id": 8,
				"name": "Wat",
				"outfit": 9,
				"home": "cabin",
				"role": "child",
				"marks": []
			},
			{
				"id": 9,
				"name": "Edith",
				"outfit": 10,
				"home": "cabin",
				"role": "child",
				"marks": []
			},
			{
				"id": 10,
				"name": "Oswin",
				"outfit": 12,
				"home": "cabin",
				"role": "child",
				"marks": []
			},
			{
				"id": 14,
				"name": "Tilda",
				"outfit": 1,
				"home": "round",
				"role": "child",
				"marks": []
			},
			{
				"id": 15,
				"name": "Orla",
				"outfit": 2,
				"home": "hill",
				"role": "miller",
				"marks": []
			},
			{
				"id": 16,
				"name": "Elsbet",
				"outfit": 9,
				"home": "round",
				"role": "miller",
				"marks": []
			},
			{
				"id": 19,
				"name": "Bettony",
				"outfit": 11,
				"home": "hill",
				"role": "miller",
				"marks": []
			},
			{
				"id": 20,
				"name": "Cecily",
				"outfit": 2,
				"home": "hill",
				"role": "herder",
				"marks": []
			},
			{
				"id": 21,
				"name": "Cuthbert",
				"outfit": 10,
				"home": "hill",
				"role": "woodcutter",
				"marks": []
			},
			{
				"id": 22,
				"name": "Ilse",
				"outfit": 5,
				"home": "hill",
				"role": "child",
				"marks": []
			},
			{
				"id": 23,
				"name": "Wenna",
				"outfit": 4,
				"home": "hill",
				"role": "midwife",
				"marks": []
			},
			{
				"id": 25,
				"name": "Juliana",
				"outfit": 6,
				"home": "lodge",
				"role": "farmer",
				"marks": []
			},
			{
				"id": 26,
				"name": "Alder",
				"outfit": 6,
				"home": "lodge",
				"role": "farmer",
				"marks": []
			},
			{
				"id": 29,
				"name": "Rolf",
				"outfit": 9,
				"home": "lodge",
				"role": "child",
				"marks": []
			},
			{
				"id": 30,
				"name": "Piers",
				"outfit": 2,
				"home": "loaf",
				"role": "miller",
				"marks": []
			},
			{
				"id": 31,
				"name": "Joan",
				"outfit": 11,
				"home": "loaf",
				"role": "herder",
				"marks": []
			},
			{
				"id": 32,
				"name": "Hugh",
				"outfit": 0,
				"home": "loaf",
				"role": "farmer",
				"marks": []
			},
			{
				"id": 33,
				"name": "Ansel",
				"outfit": 6,
				"home": "loaf",
				"role": "child",
				"marks": []
			},
			{
				"id": 34,
				"name": "Isolde",
				"outfit": 7,
				"home": "cottage",
				"role": "child",
				"marks": []
			},
			{
				"id": 35,
				"name": "Rafe",
				"outfit": 10,
				"home": "round",
				"role": "child",
				"marks": []
			},
			{
				"id": 36,
				"name": "Wystan",
				"outfit": 2,
				"home": "loaf",
				"role": "child",
				"marks": []
			},
			{
				"id": 37,
				"name": "Godric",
				"outfit": 7,
				"home": "cabin",
				"role": "child",
				"marks": []
			},
			{
				"id": 38,
				"name": "Rose",
				"outfit": 9,
				"home": "loaf",
				"role": "child",
				"marks": []
			},
			{
				"id": 39,
				"name": "Mara",
				"outfit": 1,
				"home": "hill",
				"role": "child",
				"marks": []
			},
			{
				"id": 40,
				"name": "Colm",
				"outfit": 9,
				"home": "lodge",
				"role": "child",
				"marks": []
			},
			{
				"id": 41,
				"name": "Hob",
				"outfit": 10,
				"home": "cottage",
				"role": "child",
				"marks": []
			},
			{
				"id": 42,
				"name": "Gwen",
				"outfit": 5,
				"home": "loaf",
				"role": "child",
				"marks": []
			},
			{
				"id": 43,
				"name": "Tam",
				"outfit": 10,
				"home": "loaf",
				"role": "child",
				"marks": []
			},
			{
				"id": 44,
				"name": "Bram",
				"outfit": 2,
				"home": "cabin",
				"role": "child",
				"marks": []
			},
			{
				"id": 45,
				"name": "Nell",
				"outfit": 3,
				"home": "cabin",
				"role": "child",
				"marks": []
			}
		],
		"title": "The Burning of Osric",
		"story": "Then came lights over the marsh. The old women said it meant a curse among them. Whispers started that Osric had cursed the village - charms of twisted straw found by a doorway. Tobin named Osric before the elder. Tobin, the elder, judged it too. They put Osric in the millpond. They floated. Guilty. The sentence was the fire. They burned Osric at the stake at dusk; the smoke was seen from the next valley. They are remembered as Osric the Burned."
	},
	{
		"id": 9,
		"kind": "exile",
		"place": "gate_south",
		"start": 480,
		"end": 643,
		"phases": [
			{
				"name": "gather",
				"from": 480,
				"to": 543,
				"rescue": true
			},
			{
				"name": "exile",
				"from": 543,
				"to": 593,
				"rescue": true
			},
			{
				"name": "end",
				"from": 593,
				"to": 643,
				"rescue": false
			}
		],
		"roles": {
			"victim": 5,
			"accuser": 32,
			"authority": 6,
			"crowd": [
				0,
				1,
				2,
				3,
				4,
				7,
				8,
				9,
				10,
				12,
				14,
				15,
				16,
				17,
				18,
				19,
				20,
				21,
				22,
				23,
				25,
				26,
				28,
				29,
				30,
				31,
				32,
				33,
				34,
				35,
				36,
				37,
				38,
				39,
				40
			]
		},
		"beats": [
			{
				"at": 480,
				"who": 5,
				"do": "walk_to",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 480,
				"who": 6,
				"do": "walk_to",
				"slot": -1,
				"target": 5,
				"anim": "Walk_Formal",
				"prop": ""
			},
			{
				"at": 485,
				"who": 0,
				"do": "walk_to",
				"slot": 0,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 486,
				"who": 1,
				"do": "walk_to",
				"slot": 1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 487,
				"who": 2,
				"do": "walk_to",
				"slot": 2,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 488,
				"who": 3,
				"do": "walk_to",
				"slot": 3,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 489,
				"who": 4,
				"do": "walk_to",
				"slot": 4,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 490,
				"who": 7,
				"do": "walk_to",
				"slot": 5,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 491,
				"who": 8,
				"do": "walk_to",
				"slot": 6,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 492,
				"who": 9,
				"do": "walk_to",
				"slot": 7,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 493,
				"who": 10,
				"do": "walk_to",
				"slot": 8,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 494,
				"who": 12,
				"do": "walk_to",
				"slot": 9,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 495,
				"who": 14,
				"do": "walk_to",
				"slot": 10,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 496,
				"who": 15,
				"do": "walk_to",
				"slot": 11,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 497,
				"who": 16,
				"do": "walk_to",
				"slot": 12,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 498,
				"who": 17,
				"do": "walk_to",
				"slot": 13,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 499,
				"who": 18,
				"do": "walk_to",
				"slot": 14,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 500,
				"who": 0,
				"do": "stand",
				"slot": 0,
				"target": -1,
				"anim": "Idle_Talking",
				"prop": ""
			},
			{
				"at": 500,
				"who": 19,
				"do": "walk_to",
				"slot": 15,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 501,
				"who": 1,
				"do": "stand",
				"slot": 1,
				"target": -1,
				"anim": "Idle_Talking",
				"prop": ""
			},
			{
				"at": 501,
				"who": 20,
				"do": "walk_to",
				"slot": 16,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 502,
				"who": 2,
				"do": "stand",
				"slot": 2,
				"target": -1,
				"anim": "Idle_FoldArms",
				"prop": ""
			},
			{
				"at": 502,
				"who": 21,
				"do": "walk_to",
				"slot": 17,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 503,
				"who": 3,
				"do": "stand",
				"slot": 3,
				"target": -1,
				"anim": "Idle_FoldArms",
				"prop": ""
			},
			{
				"at": 503,
				"who": 22,
				"do": "walk_to",
				"slot": 18,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 504,
				"who": 4,
				"do": "stand",
				"slot": 4,
				"target": -1,
				"anim": "Idle_FoldArms",
				"prop": ""
			},
			{
				"at": 504,
				"who": 23,
				"do": "walk_to",
				"slot": 19,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 505,
				"who": 7,
				"do": "stand",
				"slot": 5,
				"target": -1,
				"anim": "Idle_No",
				"prop": ""
			},
			{
				"at": 505,
				"who": 25,
				"do": "walk_to",
				"slot": 20,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 506,
				"who": 8,
				"do": "stand",
				"slot": 6,
				"target": -1,
				"anim": "Idle_No",
				"prop": ""
			},
			{
				"at": 506,
				"who": 12,
				"do": "stand",
				"slot": 9,
				"target": -1,
				"anim": "Idle_FoldArms",
				"prop": ""
			},
			{
				"at": 506,
				"who": 26,
				"do": "walk_to",
				"slot": 21,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 507,
				"who": 9,
				"do": "stand",
				"slot": 7,
				"target": -1,
				"anim": "Idle_No",
				"prop": ""
			},
			{
				"at": 507,
				"who": 14,
				"do": "stand",
				"slot": 10,
				"target": -1,
				"anim": "Idle_No",
				"prop": ""
			},
			{
				"at": 507,
				"who": 15,
				"do": "stand",
				"slot": 11,
				"target": -1,
				"anim": "Idle_No",
				"prop": ""
			},
			{
				"at": 507,
				"who": 28,
				"do": "walk_to",
				"slot": 22,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 508,
				"who": 10,
				"do": "stand",
				"slot": 8,
				"target": -1,
				"anim": "Idle_No",
				"prop": ""
			},
			{
				"at": 508,
				"who": 29,
				"do": "walk_to",
				"slot": 23,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 509,
				"who": 16,
				"do": "stand",
				"slot": 12,
				"target": -1,
				"anim": "Idle_No",
				"prop": ""
			},
			{
				"at": 509,
				"who": 30,
				"do": "walk_to",
				"slot": 24,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 510,
				"who": 17,
				"do": "stand",
				"slot": 13,
				"target": -1,
				"anim": "Idle_No",
				"prop": ""
			},
			{
				"at": 510,
				"who": 18,
				"do": "stand",
				"slot": 14,
				"target": -1,
				"anim": "Idle_No",
				"prop": ""
			},
			{
				"at": 510,
				"who": 31,
				"do": "walk_to",
				"slot": 25,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 511,
				"who": 19,
				"do": "stand",
				"slot": 15,
				"target": -1,
				"anim": "Idle_FoldArms",
				"prop": ""
			},
			{
				"at": 511,
				"who": 32,
				"do": "walk_to",
				"slot": 26,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 512,
				"who": 20,
				"do": "stand",
				"slot": 16,
				"target": -1,
				"anim": "Idle_No",
				"prop": ""
			},
			{
				"at": 512,
				"who": 33,
				"do": "walk_to",
				"slot": 27,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 513,
				"who": 21,
				"do": "stand",
				"slot": 17,
				"target": -1,
				"anim": "Idle_FoldArms",
				"prop": ""
			},
			{
				"at": 513,
				"who": 25,
				"do": "stand",
				"slot": 20,
				"target": -1,
				"anim": "Idle_Talking",
				"prop": ""
			},
			{
				"at": 513,
				"who": 34,
				"do": "walk_to",
				"slot": 28,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 514,
				"who": 22,
				"do": "stand",
				"slot": 18,
				"target": -1,
				"anim": "Idle_FoldArms",
				"prop": ""
			},
			{
				"at": 514,
				"who": 26,
				"do": "stand",
				"slot": 21,
				"target": -1,
				"anim": "Idle_Talking",
				"prop": ""
			},
			{
				"at": 514,
				"who": 35,
				"do": "walk_to",
				"slot": 29,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 515,
				"who": 23,
				"do": "stand",
				"slot": 19,
				"target": -1,
				"anim": "Idle_No",
				"prop": ""
			},
			{
				"at": 515,
				"who": 28,
				"do": "stand",
				"slot": 22,
				"target": -1,
				"anim": "Idle_Talking",
				"prop": ""
			},
			{
				"at": 515,
				"who": 36,
				"do": "walk_to",
				"slot": 30,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 516,
				"who": 29,
				"do": "stand",
				"slot": 23,
				"target": -1,
				"anim": "Idle_Talking",
				"prop": ""
			},
			{
				"at": 516,
				"who": 37,
				"do": "walk_to",
				"slot": 31,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 517,
				"who": 38,
				"do": "walk_to",
				"slot": 32,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 518,
				"who": 39,
				"do": "walk_to",
				"slot": 33,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 519,
				"who": 40,
				"do": "walk_to",
				"slot": 34,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 526,
				"who": 35,
				"do": "stand",
				"slot": 29,
				"target": -1,
				"anim": "Idle_FoldArms",
				"prop": ""
			},
			{
				"at": 527,
				"who": 40,
				"do": "stand",
				"slot": 34,
				"target": -1,
				"anim": "Idle_Talking",
				"prop": ""
			},
			{
				"at": 528,
				"who": 34,
				"do": "stand",
				"slot": 28,
				"target": -1,
				"anim": "Idle_FoldArms",
				"prop": ""
			},
			{
				"at": 529,
				"who": 39,
				"do": "stand",
				"slot": 33,
				"target": -1,
				"anim": "Idle_No",
				"prop": ""
			},
			{
				"at": 530,
				"who": 30,
				"do": "stand",
				"slot": 24,
				"target": -1,
				"anim": "Idle_No",
				"prop": ""
			},
			{
				"at": 531,
				"who": 31,
				"do": "stand",
				"slot": 25,
				"target": -1,
				"anim": "Idle_FoldArms",
				"prop": ""
			},
			{
				"at": 531,
				"who": 37,
				"do": "stand",
				"slot": 31,
				"target": -1,
				"anim": "Idle_No",
				"prop": ""
			},
			{
				"at": 532,
				"who": 32,
				"do": "stand",
				"slot": 26,
				"target": -1,
				"anim": "Idle_No",
				"prop": ""
			},
			{
				"at": 533,
				"who": 33,
				"do": "stand",
				"slot": 27,
				"target": -1,
				"anim": "Idle_No",
				"prop": ""
			},
			{
				"at": 536,
				"who": 36,
				"do": "stand",
				"slot": 30,
				"target": -1,
				"anim": "Idle_No",
				"prop": ""
			},
			{
				"at": 538,
				"who": 38,
				"do": "stand",
				"slot": 32,
				"target": -1,
				"anim": "Idle_No",
				"prop": ""
			},
			{
				"at": 543,
				"who": 12,
				"do": "gesture",
				"slot": -1,
				"target": -1,
				"anim": "Spell_Simple_Idle",
				"prop": ""
			},
			{
				"at": 543,
				"who": 32,
				"do": "throw",
				"slot": 26,
				"target": 5,
				"anim": "OverhandThrow",
				"prop": "cabbage"
			},
			{
				"at": 544,
				"who": 5,
				"do": "react",
				"slot": -1,
				"target": 32,
				"anim": "Hit_Chest",
				"prop": ""
			},
			{
				"at": 598,
				"who": 5,
				"do": "walk_to",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 603,
				"who": 0,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 604,
				"who": 1,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 605,
				"who": 2,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 606,
				"who": 3,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 607,
				"who": 4,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 608,
				"who": 7,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 609,
				"who": 8,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 610,
				"who": 9,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 611,
				"who": 10,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 612,
				"who": 12,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 613,
				"who": 14,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 614,
				"who": 15,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 615,
				"who": 16,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 616,
				"who": 17,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 617,
				"who": 18,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 618,
				"who": 19,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 619,
				"who": 20,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 620,
				"who": 21,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 621,
				"who": 22,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 622,
				"who": 23,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 623,
				"who": 25,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 624,
				"who": 26,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 625,
				"who": 28,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 626,
				"who": 29,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 627,
				"who": 30,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 628,
				"who": 31,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 629,
				"who": 32,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 630,
				"who": 33,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 631,
				"who": 34,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 632,
				"who": 35,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 633,
				"who": 36,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 634,
				"who": 37,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 635,
				"who": 38,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 636,
				"who": 39,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 637,
				"who": 40,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			}
		],
		"outcome": "carried_out",
		"cause": [
			"crime: a scuffle at the shrine",
			"accusation: Hugh pointing at Marjory in the square"
		],
		"cue": "Marjory led to the south gate",
		"day": 113,
		"people": [
			{
				"id": 5,
				"name": "Marjory",
				"outfit": 12,
				"home": "lodge",
				"role": "herder",
				"marks": [
					"pilloried"
				]
			},
			{
				"id": 6,
				"name": "Tobin",
				"outfit": 8,
				"home": "cabin",
				"role": "elder",
				"marks": []
			},
			{
				"id": 12,
				"name": "Garrow",
				"outfit": 0,
				"home": "round",
				"role": "priest",
				"marks": []
			},
			{
				"id": 0,
				"name": "Osric",
				"outfit": 1,
				"home": "cottage",
				"role": "farmer",
				"marks": []
			},
			{
				"id": 1,
				"name": "Maud",
				"outfit": 6,
				"home": "cottage",
				"role": "smith",
				"marks": []
			},
			{
				"id": 2,
				"name": "Dunstan",
				"outfit": 11,
				"home": "cottage",
				"role": "child",
				"marks": []
			},
			{
				"id": 3,
				"name": "Agnes",
				"outfit": 12,
				"home": "cottage",
				"role": "smith",
				"marks": []
			},
			{
				"id": 4,
				"name": "Edric",
				"outfit": 5,
				"home": "cottage",
				"role": "child",
				"marks": []
			},
			{
				"id": 7,
				"name": "Alys",
				"outfit": 11,
				"home": "cabin",
				"role": "farmer",
				"marks": []
			},
			{
				"id": 8,
				"name": "Wat",
				"outfit": 9,
				"home": "cabin",
				"role": "child",
				"marks": []
			},
			{
				"id": 9,
				"name": "Edith",
				"outfit": 10,
				"home": "cabin",
				"role": "child",
				"marks": []
			},
			{
				"id": 10,
				"name": "Oswin",
				"outfit": 12,
				"home": "cabin",
				"role": "child",
				"marks": []
			},
			{
				"id": 14,
				"name": "Tilda",
				"outfit": 1,
				"home": "round",
				"role": "child",
				"marks": []
			},
			{
				"id": 15,
				"name": "Orla",
				"outfit": 2,
				"home": "hill",
				"role": "miller",
				"marks": []
			},
			{
				"id": 16,
				"name": "Elsbet",
				"outfit": 9,
				"home": "round",
				"role": "child",
				"marks": []
			},
			{
				"id": 17,
				"name": "Merric",
				"outfit": 11,
				"home": "round",
				"role": "midwife",
				"marks": []
			},
			{
				"id": 18,
				"name": "Aldric",
				"outfit": 7,
				"home": "hill",
				"role": "midwife",
				"marks": []
			},
			{
				"id": 19,
				"name": "Bettony",
				"outfit": 11,
				"home": "hill",
				"role": "miller",
				"marks": []
			},
			{
				"id": 20,
				"name": "Cecily",
				"outfit": 2,
				"home": "hill",
				"role": "herder",
				"marks": []
			},
			{
				"id": 21,
				"name": "Cuthbert",
				"outfit": 10,
				"home": "hill",
				"role": "woodcutter",
				"marks": []
			},
			{
				"id": 22,
				"name": "Ilse",
				"outfit": 5,
				"home": "hill",
				"role": "child",
				"marks": []
			},
			{
				"id": 23,
				"name": "Wenna",
				"outfit": 4,
				"home": "hill",
				"role": "child",
				"marks": []
			},
			{
				"id": 25,
				"name": "Juliana",
				"outfit": 6,
				"home": "lodge",
				"role": "farmer",
				"marks": []
			},
			{
				"id": 26,
				"name": "Alder",
				"outfit": 6,
				"home": "lodge",
				"role": "farmer",
				"marks": []
			},
			{
				"id": 28,
				"name": "Simkin",
				"outfit": 10,
				"home": "lodge",
				"role": "miller",
				"marks": []
			},
			{
				"id": 29,
				"name": "Rolf",
				"outfit": 9,
				"home": "lodge",
				"role": "child",
				"marks": []
			},
			{
				"id": 30,
				"name": "Piers",
				"outfit": 2,
				"home": "loaf",
				"role": "miller",
				"marks": []
			},
			{
				"id": 31,
				"name": "Joan",
				"outfit": 11,
				"home": "loaf",
				"role": "herder",
				"marks": []
			},
			{
				"id": 32,
				"name": "Hugh",
				"outfit": 0,
				"home": "loaf",
				"role": "farmer",
				"marks": []
			},
			{
				"id": 33,
				"name": "Ansel",
				"outfit": 6,
				"home": "loaf",
				"role": "child",
				"marks": []
			},
			{
				"id": 34,
				"name": "Isolde",
				"outfit": 7,
				"home": "cottage",
				"role": "child",
				"marks": []
			},
			{
				"id": 35,
				"name": "Rafe",
				"outfit": 10,
				"home": "round",
				"role": "child",
				"marks": []
			},
			{
				"id": 36,
				"name": "Wystan",
				"outfit": 2,
				"home": "loaf",
				"role": "child",
				"marks": []
			},
			{
				"id": 37,
				"name": "Godric",
				"outfit": 7,
				"home": "cabin",
				"role": "child",
				"marks": []
			},
			{
				"id": 38,
				"name": "Rose",
				"outfit": 9,
				"home": "loaf",
				"role": "child",
				"marks": []
			},
			{
				"id": 39,
				"name": "Mara",
				"outfit": 1,
				"home": "hill",
				"role": "child",
				"marks": []
			},
			{
				"id": 40,
				"name": "Colm",
				"outfit": 9,
				"home": "lodge",
				"role": "child",
				"marks": []
			}
		],
		"title": "Marjory Walks Out",
		"story": "One evening old grudges came to blows: Marjory struck Hugh. Hugh named Marjory before the elder. Tobin, the elder, heard it in the square. The sentence was exile."
	},
	{
		"id": 2,
		"kind": "trial",
		"place": "square",
		"start": 480,
		"end": 580,
		"phases": [
			{
				"name": "gather",
				"from": 480,
				"to": 540,
				"rescue": true
			},
			{
				"name": "fine",
				"from": 540,
				"to": 530,
				"rescue": true
			},
			{
				"name": "end",
				"from": 530,
				"to": 580,
				"rescue": false
			}
		],
		"roles": {
			"victim": 5,
			"accuser": 31,
			"authority": 6,
			"crowd": [
				0,
				1,
				2,
				3,
				4,
				7,
				8,
				9,
				10,
				12,
				13,
				14,
				15,
				16,
				17,
				18,
				19,
				20,
				21,
				22,
				23,
				24,
				25,
				26,
				27,
				28,
				29,
				30,
				31,
				32,
				33,
				34,
				35,
				36,
				37
			]
		},
		"beats": [
			{
				"at": 480,
				"who": 5,
				"do": "walk_to",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 480,
				"who": 6,
				"do": "walk_to",
				"slot": -1,
				"target": 5,
				"anim": "Walk_Formal",
				"prop": ""
			},
			{
				"at": 485,
				"who": 0,
				"do": "walk_to",
				"slot": 0,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 486,
				"who": 1,
				"do": "walk_to",
				"slot": 1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 487,
				"who": 2,
				"do": "walk_to",
				"slot": 2,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 488,
				"who": 3,
				"do": "walk_to",
				"slot": 3,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 489,
				"who": 4,
				"do": "walk_to",
				"slot": 4,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 490,
				"who": 7,
				"do": "walk_to",
				"slot": 5,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 491,
				"who": 0,
				"do": "stand",
				"slot": 0,
				"target": -1,
				"anim": "Idle_Talking",
				"prop": ""
			},
			{
				"at": 491,
				"who": 8,
				"do": "walk_to",
				"slot": 6,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 492,
				"who": 1,
				"do": "stand",
				"slot": 1,
				"target": -1,
				"anim": "Idle_Talking",
				"prop": ""
			},
			{
				"at": 492,
				"who": 9,
				"do": "walk_to",
				"slot": 7,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 493,
				"who": 2,
				"do": "stand",
				"slot": 2,
				"target": -1,
				"anim": "Idle_Talking",
				"prop": ""
			},
			{
				"at": 493,
				"who": 10,
				"do": "walk_to",
				"slot": 8,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 494,
				"who": 3,
				"do": "stand",
				"slot": 3,
				"target": -1,
				"anim": "Idle_Talking",
				"prop": ""
			},
			{
				"at": 494,
				"who": 12,
				"do": "walk_to",
				"slot": 9,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 495,
				"who": 4,
				"do": "stand",
				"slot": 4,
				"target": -1,
				"anim": "Idle_Talking",
				"prop": ""
			},
			{
				"at": 495,
				"who": 13,
				"do": "walk_to",
				"slot": 10,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 496,
				"who": 14,
				"do": "walk_to",
				"slot": 11,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 497,
				"who": 7,
				"do": "stand",
				"slot": 5,
				"target": -1,
				"anim": "Idle_No",
				"prop": ""
			},
			{
				"at": 497,
				"who": 15,
				"do": "walk_to",
				"slot": 12,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 498,
				"who": 8,
				"do": "stand",
				"slot": 6,
				"target": -1,
				"anim": "Idle_No",
				"prop": ""
			},
			{
				"at": 498,
				"who": 16,
				"do": "walk_to",
				"slot": 13,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 499,
				"who": 9,
				"do": "stand",
				"slot": 7,
				"target": -1,
				"anim": "Idle_No",
				"prop": ""
			},
			{
				"at": 499,
				"who": 17,
				"do": "walk_to",
				"slot": 14,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 500,
				"who": 10,
				"do": "stand",
				"slot": 8,
				"target": -1,
				"anim": "Idle_No",
				"prop": ""
			},
			{
				"at": 500,
				"who": 18,
				"do": "walk_to",
				"slot": 15,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 501,
				"who": 19,
				"do": "walk_to",
				"slot": 16,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 502,
				"who": 12,
				"do": "stand",
				"slot": 9,
				"target": -1,
				"anim": "Idle_FoldArms",
				"prop": ""
			},
			{
				"at": 502,
				"who": 20,
				"do": "walk_to",
				"slot": 17,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 503,
				"who": 13,
				"do": "stand",
				"slot": 10,
				"target": -1,
				"anim": "Idle_No",
				"prop": ""
			},
			{
				"at": 503,
				"who": 21,
				"do": "walk_to",
				"slot": 18,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 504,
				"who": 14,
				"do": "stand",
				"slot": 11,
				"target": -1,
				"anim": "Idle_No",
				"prop": ""
			},
			{
				"at": 504,
				"who": 22,
				"do": "walk_to",
				"slot": 19,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 505,
				"who": 15,
				"do": "stand",
				"slot": 12,
				"target": -1,
				"anim": "Idle_No",
				"prop": ""
			},
			{
				"at": 505,
				"who": 23,
				"do": "walk_to",
				"slot": 20,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 506,
				"who": 16,
				"do": "stand",
				"slot": 13,
				"target": -1,
				"anim": "Idle_No",
				"prop": ""
			},
			{
				"at": 506,
				"who": 18,
				"do": "stand",
				"slot": 15,
				"target": -1,
				"anim": "Idle_No",
				"prop": ""
			},
			{
				"at": 506,
				"who": 24,
				"do": "walk_to",
				"slot": 21,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 507,
				"who": 17,
				"do": "stand",
				"slot": 14,
				"target": -1,
				"anim": "Idle_No",
				"prop": ""
			},
			{
				"at": 507,
				"who": 19,
				"do": "stand",
				"slot": 16,
				"target": -1,
				"anim": "Idle_FoldArms",
				"prop": ""
			},
			{
				"at": 507,
				"who": 25,
				"do": "walk_to",
				"slot": 22,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 508,
				"who": 20,
				"do": "stand",
				"slot": 17,
				"target": -1,
				"anim": "Idle_FoldArms",
				"prop": ""
			},
			{
				"at": 508,
				"who": 26,
				"do": "walk_to",
				"slot": 23,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 509,
				"who": 21,
				"do": "stand",
				"slot": 18,
				"target": -1,
				"anim": "Idle_No",
				"prop": ""
			},
			{
				"at": 509,
				"who": 27,
				"do": "walk_to",
				"slot": 24,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 510,
				"who": 22,
				"do": "stand",
				"slot": 19,
				"target": -1,
				"anim": "Idle_FoldArms",
				"prop": ""
			},
			{
				"at": 510,
				"who": 28,
				"do": "walk_to",
				"slot": 25,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 511,
				"who": 23,
				"do": "stand",
				"slot": 20,
				"target": -1,
				"anim": "Idle_FoldArms",
				"prop": ""
			},
			{
				"at": 511,
				"who": 29,
				"do": "walk_to",
				"slot": 26,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 512,
				"who": 30,
				"do": "walk_to",
				"slot": 27,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 513,
				"who": 31,
				"do": "walk_to",
				"slot": 28,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 514,
				"who": 32,
				"do": "walk_to",
				"slot": 29,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 515,
				"who": 24,
				"do": "stand",
				"slot": 21,
				"target": -1,
				"anim": "Idle_FoldArms",
				"prop": ""
			},
			{
				"at": 515,
				"who": 33,
				"do": "walk_to",
				"slot": 30,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 516,
				"who": 25,
				"do": "stand",
				"slot": 22,
				"target": -1,
				"anim": "Idle_No",
				"prop": ""
			},
			{
				"at": 516,
				"who": 34,
				"do": "walk_to",
				"slot": 31,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 517,
				"who": 26,
				"do": "stand",
				"slot": 23,
				"target": -1,
				"anim": "Idle_No",
				"prop": ""
			},
			{
				"at": 517,
				"who": 35,
				"do": "walk_to",
				"slot": 32,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 518,
				"who": 27,
				"do": "stand",
				"slot": 24,
				"target": -1,
				"anim": "Idle_No",
				"prop": ""
			},
			{
				"at": 518,
				"who": 36,
				"do": "walk_to",
				"slot": 33,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 519,
				"who": 28,
				"do": "stand",
				"slot": 25,
				"target": -1,
				"anim": "Idle_No",
				"prop": ""
			},
			{
				"at": 519,
				"who": 37,
				"do": "walk_to",
				"slot": 34,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 520,
				"who": 29,
				"do": "stand",
				"slot": 26,
				"target": -1,
				"anim": "Idle_No",
				"prop": ""
			},
			{
				"at": 522,
				"who": 34,
				"do": "stand",
				"slot": 31,
				"target": -1,
				"anim": "Idle_Talking",
				"prop": ""
			},
			{
				"at": 525,
				"who": 30,
				"do": "stand",
				"slot": 27,
				"target": -1,
				"anim": "Idle_No",
				"prop": ""
			},
			{
				"at": 525,
				"who": 35,
				"do": "stand",
				"slot": 32,
				"target": -1,
				"anim": "Idle_No",
				"prop": ""
			},
			{
				"at": 526,
				"who": 31,
				"do": "stand",
				"slot": 28,
				"target": -1,
				"anim": "Idle_No",
				"prop": ""
			},
			{
				"at": 526,
				"who": 37,
				"do": "stand",
				"slot": 34,
				"target": -1,
				"anim": "Idle_No",
				"prop": ""
			},
			{
				"at": 527,
				"who": 32,
				"do": "stand",
				"slot": 29,
				"target": -1,
				"anim": "Idle_No",
				"prop": ""
			},
			{
				"at": 528,
				"who": 33,
				"do": "stand",
				"slot": 30,
				"target": -1,
				"anim": "Idle_No",
				"prop": ""
			},
			{
				"at": 531,
				"who": 36,
				"do": "stand",
				"slot": 33,
				"target": -1,
				"anim": "Idle_No",
				"prop": ""
			},
			{
				"at": 535,
				"who": 5,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 540,
				"who": 0,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 541,
				"who": 1,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 542,
				"who": 2,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 543,
				"who": 3,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 544,
				"who": 4,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 545,
				"who": 7,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 546,
				"who": 8,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 547,
				"who": 9,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 548,
				"who": 10,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 549,
				"who": 12,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 550,
				"who": 13,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 551,
				"who": 14,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 552,
				"who": 15,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 553,
				"who": 16,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 554,
				"who": 17,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 555,
				"who": 18,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 556,
				"who": 19,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 557,
				"who": 20,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 558,
				"who": 21,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 559,
				"who": 22,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 560,
				"who": 23,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 561,
				"who": 24,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 562,
				"who": 25,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 563,
				"who": 26,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 564,
				"who": 27,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 565,
				"who": 28,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 566,
				"who": 29,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 567,
				"who": 30,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 568,
				"who": 31,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 569,
				"who": 32,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 570,
				"who": 33,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 571,
				"who": 34,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 572,
				"who": 35,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 573,
				"who": 36,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 574,
				"who": 37,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			}
		],
		"outcome": "confessed_spared",
		"cause": [
			"crime: a scuffle at the shrine",
			"accusation: Joan pointing at Marjory in the square"
		],
		"cue": "coins counted out on the elder's bench",
		"day": 54,
		"people": [
			{
				"id": 5,
				"name": "Marjory",
				"outfit": 12,
				"home": "cottage",
				"role": "herder",
				"marks": []
			},
			{
				"id": 6,
				"name": "Tobin",
				"outfit": 8,
				"home": "cabin",
				"role": "elder",
				"marks": []
			},
			{
				"id": 12,
				"name": "Garrow",
				"outfit": 0,
				"home": "round",
				"role": "priest",
				"marks": []
			},
			{
				"id": 0,
				"name": "Osric",
				"outfit": 1,
				"home": "cottage",
				"role": "farmer",
				"marks": []
			},
			{
				"id": 1,
				"name": "Maud",
				"outfit": 6,
				"home": "cottage",
				"role": "smith",
				"marks": []
			},
			{
				"id": 2,
				"name": "Dunstan",
				"outfit": 11,
				"home": "cottage",
				"role": "child",
				"marks": []
			},
			{
				"id": 3,
				"name": "Agnes",
				"outfit": 12,
				"home": "cottage",
				"role": "smith",
				"marks": []
			},
			{
				"id": 4,
				"name": "Edric",
				"outfit": 5,
				"home": "cottage",
				"role": "child",
				"marks": []
			},
			{
				"id": 7,
				"name": "Alys",
				"outfit": 11,
				"home": "cabin",
				"role": "farmer",
				"marks": []
			},
			{
				"id": 8,
				"name": "Wat",
				"outfit": 9,
				"home": "cabin",
				"role": "child",
				"marks": []
			},
			{
				"id": 9,
				"name": "Edith",
				"outfit": 10,
				"home": "cabin",
				"role": "child",
				"marks": []
			},
			{
				"id": 10,
				"name": "Oswin",
				"outfit": 12,
				"home": "cabin",
				"role": "child",
				"marks": []
			},
			{
				"id": 13,
				"name": "Gwen",
				"outfit": 8,
				"home": "round",
				"role": "farmer",
				"marks": []
			},
			{
				"id": 14,
				"name": "Tilda",
				"outfit": 1,
				"home": "round",
				"role": "child",
				"marks": []
			},
			{
				"id": 15,
				"name": "Orla",
				"outfit": 2,
				"home": "round",
				"role": "miller",
				"marks": []
			},
			{
				"id": 16,
				"name": "Elsbet",
				"outfit": 9,
				"home": "round",
				"role": "child",
				"marks": []
			},
			{
				"id": 17,
				"name": "Merric",
				"outfit": 11,
				"home": "round",
				"role": "child",
				"marks": []
			},
			{
				"id": 18,
				"name": "Aldric",
				"outfit": 7,
				"home": "hill",
				"role": "midwife",
				"marks": []
			},
			{
				"id": 19,
				"name": "Bettony",
				"outfit": 11,
				"home": "hill",
				"role": "miller",
				"marks": []
			},
			{
				"id": 20,
				"name": "Cecily",
				"outfit": 2,
				"home": "hill",
				"role": "child",
				"marks": []
			},
			{
				"id": 21,
				"name": "Cuthbert",
				"outfit": 10,
				"home": "hill",
				"role": "woodcutter",
				"marks": []
			},
			{
				"id": 22,
				"name": "Ilse",
				"outfit": 5,
				"home": "hill",
				"role": "child",
				"marks": []
			},
			{
				"id": 23,
				"name": "Wenna",
				"outfit": 4,
				"home": "hill",
				"role": "child",
				"marks": []
			},
			{
				"id": 24,
				"name": "Jory",
				"outfit": 11,
				"home": "lodge",
				"role": "herder",
				"marks": []
			},
			{
				"id": 25,
				"name": "Juliana",
				"outfit": 6,
				"home": "lodge",
				"role": "farmer",
				"marks": []
			},
			{
				"id": 26,
				"name": "Alder",
				"outfit": 6,
				"home": "lodge",
				"role": "farmer",
				"marks": []
			},
			{
				"id": 27,
				"name": "Colm",
				"outfit": 0,
				"home": "lodge",
				"role": "child",
				"marks": []
			},
			{
				"id": 28,
				"name": "Simkin",
				"outfit": 10,
				"home": "lodge",
				"role": "miller",
				"marks": []
			},
			{
				"id": 29,
				"name": "Rolf",
				"outfit": 9,
				"home": "lodge",
				"role": "child",
				"marks": []
			},
			{
				"id": 30,
				"name": "Piers",
				"outfit": 2,
				"home": "loaf",
				"role": "miller",
				"marks": []
			},
			{
				"id": 31,
				"name": "Joan",
				"outfit": 11,
				"home": "loaf",
				"role": "herder",
				"marks": []
			},
			{
				"id": 32,
				"name": "Hugh",
				"outfit": 0,
				"home": "loaf",
				"role": "farmer",
				"marks": []
			},
			{
				"id": 33,
				"name": "Ansel",
				"outfit": 6,
				"home": "loaf",
				"role": "child",
				"marks": []
			},
			{
				"id": 34,
				"name": "Isolde",
				"outfit": 7,
				"home": "cottage",
				"role": "child",
				"marks": []
			},
			{
				"id": 35,
				"name": "Rafe",
				"outfit": 10,
				"home": "round",
				"role": "child",
				"marks": []
			},
			{
				"id": 36,
				"name": "Wystan",
				"outfit": 2,
				"home": "loaf",
				"role": "child",
				"marks": []
			},
			{
				"id": 37,
				"name": "Godric",
				"outfit": 7,
				"home": "cabin",
				"role": "child",
				"marks": []
			}
		],
		"title": "Marjory's Fine",
		"story": "One evening old grudges came to blows: Marjory struck Hugh. Joan named Marjory before the elder. Tobin, the elder, heard it in the square. Marjory confessed, and was spared the worst. The sentence was a fine. Marjory paid in grain. They are remembered as Marjory Who Confessed."
	},
	{
		"id": 0,
		"kind": "festival",
		"place": "square",
		"start": 1080,
		"end": 1340,
		"phases": [
			{
				"name": "feast",
				"from": 1080,
				"to": 1300,
				"rescue": false
			}
		],
		"roles": {
			"victim": -1,
			"accuser": -1,
			"authority": 11,
			"crowd": [
				0,
				1,
				2,
				3,
				4,
				5,
				6,
				7,
				8,
				9,
				10,
				11,
				12,
				13,
				14,
				15,
				16,
				17,
				18,
				19,
				20,
				21,
				22,
				23,
				24,
				25,
				26,
				27,
				28,
				29
			]
		},
		"beats": [
			{
				"at": 1080,
				"who": 0,
				"do": "walk_to",
				"slot": 0,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 1081,
				"who": 1,
				"do": "walk_to",
				"slot": 1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 1082,
				"who": 2,
				"do": "walk_to",
				"slot": 2,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 1083,
				"who": 3,
				"do": "walk_to",
				"slot": 3,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 1084,
				"who": 4,
				"do": "walk_to",
				"slot": 4,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 1085,
				"who": 5,
				"do": "walk_to",
				"slot": 5,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 1086,
				"who": 6,
				"do": "walk_to",
				"slot": 6,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 1087,
				"who": 7,
				"do": "walk_to",
				"slot": 7,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 1088,
				"who": 8,
				"do": "walk_to",
				"slot": 8,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 1089,
				"who": 9,
				"do": "walk_to",
				"slot": 9,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 1090,
				"who": 10,
				"do": "walk_to",
				"slot": 10,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 1091,
				"who": 11,
				"do": "walk_to",
				"slot": 11,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 1092,
				"who": 12,
				"do": "walk_to",
				"slot": 12,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 1093,
				"who": 13,
				"do": "walk_to",
				"slot": 13,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 1094,
				"who": 14,
				"do": "walk_to",
				"slot": 14,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 1095,
				"who": 15,
				"do": "walk_to",
				"slot": 15,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 1096,
				"who": 16,
				"do": "walk_to",
				"slot": 16,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 1097,
				"who": 17,
				"do": "walk_to",
				"slot": 17,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 1098,
				"who": 18,
				"do": "walk_to",
				"slot": 18,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 1099,
				"who": 19,
				"do": "walk_to",
				"slot": 19,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 1100,
				"who": 20,
				"do": "walk_to",
				"slot": 20,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 1101,
				"who": 21,
				"do": "walk_to",
				"slot": 21,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 1102,
				"who": 22,
				"do": "walk_to",
				"slot": 22,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 1103,
				"who": 23,
				"do": "walk_to",
				"slot": 23,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 1104,
				"who": 24,
				"do": "walk_to",
				"slot": 24,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 1105,
				"who": 25,
				"do": "walk_to",
				"slot": 25,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 1106,
				"who": 26,
				"do": "walk_to",
				"slot": 26,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 1107,
				"who": 27,
				"do": "walk_to",
				"slot": 27,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 1108,
				"who": 28,
				"do": "walk_to",
				"slot": 28,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 1109,
				"who": 29,
				"do": "walk_to",
				"slot": 29,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 1110,
				"who": 0,
				"do": "stand",
				"slot": 0,
				"target": -1,
				"anim": "Idle_Talking",
				"prop": ""
			},
			{
				"at": 1111,
				"who": 1,
				"do": "stand",
				"slot": 1,
				"target": -1,
				"anim": "Dance",
				"prop": ""
			},
			{
				"at": 1112,
				"who": 2,
				"do": "stand",
				"slot": 2,
				"target": -1,
				"anim": "Dance",
				"prop": ""
			},
			{
				"at": 1113,
				"who": 3,
				"do": "stand",
				"slot": 3,
				"target": -1,
				"anim": "Idle_Talking",
				"prop": ""
			},
			{
				"at": 1114,
				"who": 4,
				"do": "stand",
				"slot": 4,
				"target": -1,
				"anim": "Dance",
				"prop": ""
			},
			{
				"at": 1115,
				"who": 5,
				"do": "stand",
				"slot": 5,
				"target": -1,
				"anim": "Dance",
				"prop": ""
			},
			{
				"at": 1116,
				"who": 6,
				"do": "stand",
				"slot": 6,
				"target": -1,
				"anim": "Idle_Talking",
				"prop": ""
			},
			{
				"at": 1117,
				"who": 7,
				"do": "stand",
				"slot": 7,
				"target": -1,
				"anim": "Dance",
				"prop": ""
			},
			{
				"at": 1118,
				"who": 8,
				"do": "stand",
				"slot": 8,
				"target": -1,
				"anim": "Dance",
				"prop": ""
			},
			{
				"at": 1119,
				"who": 9,
				"do": "stand",
				"slot": 9,
				"target": -1,
				"anim": "Idle_Talking",
				"prop": ""
			},
			{
				"at": 1120,
				"who": 10,
				"do": "stand",
				"slot": 10,
				"target": -1,
				"anim": "Dance",
				"prop": ""
			},
			{
				"at": 1121,
				"who": 11,
				"do": "stand",
				"slot": 11,
				"target": -1,
				"anim": "Dance",
				"prop": ""
			},
			{
				"at": 1122,
				"who": 12,
				"do": "stand",
				"slot": 12,
				"target": -1,
				"anim": "Idle_Talking",
				"prop": ""
			},
			{
				"at": 1123,
				"who": 13,
				"do": "stand",
				"slot": 13,
				"target": -1,
				"anim": "Dance",
				"prop": ""
			},
			{
				"at": 1124,
				"who": 14,
				"do": "stand",
				"slot": 14,
				"target": -1,
				"anim": "Dance",
				"prop": ""
			},
			{
				"at": 1125,
				"who": 15,
				"do": "stand",
				"slot": 15,
				"target": -1,
				"anim": "Idle_Talking",
				"prop": ""
			},
			{
				"at": 1126,
				"who": 16,
				"do": "stand",
				"slot": 16,
				"target": -1,
				"anim": "Dance",
				"prop": ""
			},
			{
				"at": 1127,
				"who": 17,
				"do": "stand",
				"slot": 17,
				"target": -1,
				"anim": "Dance",
				"prop": ""
			},
			{
				"at": 1128,
				"who": 18,
				"do": "stand",
				"slot": 18,
				"target": -1,
				"anim": "Idle_Talking",
				"prop": ""
			},
			{
				"at": 1129,
				"who": 19,
				"do": "stand",
				"slot": 19,
				"target": -1,
				"anim": "Dance",
				"prop": ""
			},
			{
				"at": 1130,
				"who": 20,
				"do": "stand",
				"slot": 20,
				"target": -1,
				"anim": "Dance",
				"prop": ""
			},
			{
				"at": 1131,
				"who": 21,
				"do": "stand",
				"slot": 21,
				"target": -1,
				"anim": "Idle_Talking",
				"prop": ""
			},
			{
				"at": 1132,
				"who": 22,
				"do": "stand",
				"slot": 22,
				"target": -1,
				"anim": "Dance",
				"prop": ""
			},
			{
				"at": 1133,
				"who": 23,
				"do": "stand",
				"slot": 23,
				"target": -1,
				"anim": "Dance",
				"prop": ""
			},
			{
				"at": 1134,
				"who": 24,
				"do": "stand",
				"slot": 24,
				"target": -1,
				"anim": "Idle_Talking",
				"prop": ""
			},
			{
				"at": 1135,
				"who": 25,
				"do": "stand",
				"slot": 25,
				"target": -1,
				"anim": "Dance",
				"prop": ""
			},
			{
				"at": 1136,
				"who": 26,
				"do": "stand",
				"slot": 26,
				"target": -1,
				"anim": "Dance",
				"prop": ""
			},
			{
				"at": 1137,
				"who": 27,
				"do": "stand",
				"slot": 27,
				"target": -1,
				"anim": "Idle_Talking",
				"prop": ""
			},
			{
				"at": 1138,
				"who": 28,
				"do": "stand",
				"slot": 28,
				"target": -1,
				"anim": "Dance",
				"prop": ""
			},
			{
				"at": 1139,
				"who": 29,
				"do": "stand",
				"slot": 29,
				"target": -1,
				"anim": "Dance",
				"prop": ""
			},
			{
				"at": 1300,
				"who": 0,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 1301,
				"who": 1,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 1302,
				"who": 2,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 1303,
				"who": 3,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 1304,
				"who": 4,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 1305,
				"who": 5,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 1306,
				"who": 6,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 1307,
				"who": 7,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 1308,
				"who": 8,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 1309,
				"who": 9,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 1310,
				"who": 10,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 1311,
				"who": 11,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 1312,
				"who": 12,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 1313,
				"who": 13,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 1314,
				"who": 14,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 1315,
				"who": 15,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 1316,
				"who": 16,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 1317,
				"who": 17,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 1318,
				"who": 18,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 1319,
				"who": 19,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 1320,
				"who": 20,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 1321,
				"who": 21,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 1322,
				"who": 22,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 1323,
				"who": 23,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 1324,
				"who": 24,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 1325,
				"who": 25,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 1326,
				"who": 26,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 1327,
				"who": 27,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 1328,
				"who": 28,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			},
			{
				"at": 1329,
				"who": 29,
				"do": "leave",
				"slot": -1,
				"target": -1,
				"anim": "Walk",
				"prop": ""
			}
		],
		"outcome": "carried_out",
		"cause": [
			"Midsummer"
		],
		"cue": "dancing in the square",
		"day": 22,
		"people": [
			{
				"id": 0,
				"name": "Osric",
				"outfit": 1,
				"home": "cottage",
				"role": "farmer",
				"marks": []
			},
			{
				"id": 1,
				"name": "Maud",
				"outfit": 6,
				"home": "cottage",
				"role": "smith",
				"marks": []
			},
			{
				"id": 2,
				"name": "Dunstan",
				"outfit": 11,
				"home": "cottage",
				"role": "child",
				"marks": []
			},
			{
				"id": 3,
				"name": "Agnes",
				"outfit": 12,
				"home": "cottage",
				"role": "smith",
				"marks": []
			},
			{
				"id": 4,
				"name": "Edric",
				"outfit": 5,
				"home": "cottage",
				"role": "child",
				"marks": []
			},
			{
				"id": 5,
				"name": "Marjory",
				"outfit": 12,
				"home": "cottage",
				"role": "herder",
				"marks": []
			},
			{
				"id": 6,
				"name": "Tobin",
				"outfit": 8,
				"home": "cabin",
				"role": "midwife",
				"marks": []
			},
			{
				"id": 7,
				"name": "Alys",
				"outfit": 11,
				"home": "cabin",
				"role": "farmer",
				"marks": []
			},
			{
				"id": 8,
				"name": "Wat",
				"outfit": 9,
				"home": "cabin",
				"role": "child",
				"marks": []
			},
			{
				"id": 9,
				"name": "Edith",
				"outfit": 10,
				"home": "cabin",
				"role": "child",
				"marks": []
			},
			{
				"id": 10,
				"name": "Oswin",
				"outfit": 12,
				"home": "cabin",
				"role": "child",
				"marks": []
			},
			{
				"id": 11,
				"name": "Bram",
				"outfit": 10,
				"home": "cabin",
				"role": "elder",
				"marks": []
			},
			{
				"id": 12,
				"name": "Garrow",
				"outfit": 0,
				"home": "round",
				"role": "priest",
				"marks": []
			},
			{
				"id": 13,
				"name": "Gwen",
				"outfit": 8,
				"home": "round",
				"role": "farmer",
				"marks": []
			},
			{
				"id": 14,
				"name": "Tilda",
				"outfit": 1,
				"home": "round",
				"role": "child",
				"marks": []
			},
			{
				"id": 15,
				"name": "Orla",
				"outfit": 2,
				"home": "round",
				"role": "miller",
				"marks": []
			},
			{
				"id": 16,
				"name": "Elsbet",
				"outfit": 9,
				"home": "round",
				"role": "child",
				"marks": []
			},
			{
				"id": 17,
				"name": "Merric",
				"outfit": 11,
				"home": "round",
				"role": "child",
				"marks": []
			},
			{
				"id": 18,
				"name": "Aldric",
				"outfit": 7,
				"home": "hill",
				"role": "midwife",
				"marks": []
			},
			{
				"id": 19,
				"name": "Bettony",
				"outfit": 11,
				"home": "hill",
				"role": "miller",
				"marks": []
			},
			{
				"id": 20,
				"name": "Cecily",
				"outfit": 2,
				"home": "hill",
				"role": "child",
				"marks": []
			},
			{
				"id": 21,
				"name": "Cuthbert",
				"outfit": 10,
				"home": "hill",
				"role": "woodcutter",
				"marks": []
			},
			{
				"id": 22,
				"name": "Ilse",
				"outfit": 5,
				"home": "hill",
				"role": "child",
				"marks": []
			},
			{
				"id": 23,
				"name": "Wenna",
				"outfit": 4,
				"home": "hill",
				"role": "child",
				"marks": []
			},
			{
				"id": 24,
				"name": "Jory",
				"outfit": 11,
				"home": "lodge",
				"role": "herder",
				"marks": []
			},
			{
				"id": 25,
				"name": "Juliana",
				"outfit": 6,
				"home": "lodge",
				"role": "farmer",
				"marks": []
			},
			{
				"id": 26,
				"name": "Alder",
				"outfit": 6,
				"home": "lodge",
				"role": "farmer",
				"marks": []
			},
			{
				"id": 27,
				"name": "Colm",
				"outfit": 0,
				"home": "lodge",
				"role": "child",
				"marks": []
			},
			{
				"id": 28,
				"name": "Simkin",
				"outfit": 10,
				"home": "lodge",
				"role": "miller",
				"marks": []
			},
			{
				"id": 29,
				"name": "Rolf",
				"outfit": 9,
				"home": "lodge",
				"role": "child",
				"marks": []
			}
		],
		"title": "festival",
		"story": "dancing in the square"
	}
]
