extends RefCounted
## Regenerates golden_data.gd from the GDScript rules, in the format golden.mjs wrote (the JavaScript reference
## is frozen; after a change to the rules this is how the golden checkpoints move).
##
##   godot --headless --path game --script res://scripts/studio/run.gd -- village/sim/golden_gd [out]
##
## `out` is where to write (default user://golden_data_gd.gd, so nothing committed is touched). To replace the
## committed golden, name it: res://scripts/studio/village/sim/golden_data.gd. The written file carries
## `const SOURCE`, which conformance.gd prints so a report says who generated the golden it compared against.
## The report also says whether the numbers equal the committed golden's (they do while the rules are the
## ones the JavaScript reference was ported from).
const C := preload("res://scripts/studio/village/sim/content.gd")
const Conformance := preload("res://scripts/studio/village/sim/conformance.gd")
const Golden := preload("res://scripts/studio/village/sim/golden_data.gd")

const SOURCE := "the GDScript rules (golden_gd.gd)"
const EVERY := 30   # days between checkpoints (conformance.gd reads it from the golden it loads)
const DEFAULT_OUT := "user://golden_data_gd.gd"


## The cases, as golden.mjs had them: [seed, pace, years].
static func cases() -> Array:
	return [
		{"seed": 1000, "pace": 1, "years": 10},
		{"seed": 8919, "pace": 1, "years": 10},
		{"seed": 16838, "pace": C.LIVE_PACE, "years": 10},
	]


## The golden file's text for these rows (golden.mjs: JSON in tabs, keys in the order seed, pace, years, checks, final).
static func file_text(rows: Array) -> String:
	return "# Generated by scripts/studio/village/sim/golden_gd.gd from the GDScript rules - do not edit by hand.\n" \
		+ "# The GDScript rules' hashes at checkpoints; conformance.gd runs the same rules again and must reproduce every one.\n" \
		+ "# Each check: [day, village hash, event-log hash, events so far, hash of the stagings made since the last\n" \
		+ "# check (conformance.gd hash_stagings), how many].\n" \
		+ "extends RefCounted\n\n" \
		+ "const SOURCE := \"%s\"\n" % SOURCE \
		+ "const EVERY := %d\n" % EVERY \
		+ "const CASES := %s\n" % JSON.stringify(rows, "\t", false)


static func report() -> PackedStringArray:
	var args := OS.get_cmdline_user_args()
	var out_path := args[1] if args.size() > 1 else DEFAULT_OUT
	var lines := PackedStringArray()
	if Golden.EVERY != EVERY:
		return ["FAIL golden_gd: the committed golden checks every %d days, this writes every %d" % [Golden.EVERY, EVERY]]
	var rows := []
	var total_ms := 0.0
	for c: Dictionary in cases():
		var ran := Conformance.simulate(c)
		var row := c.duplicate()
		row["checks"] = ran["rows"]
		row["final"] = ran["final"]
		rows.append(row)
		total_ms += ran["usec"] / 1000.0
		lines.append("seed %d pace %d: %d checkpoints, final %s" % [c["seed"], c["pace"], ran["rows"].size(), JSON.stringify(ran["final"])])
	var same := true
	var committed: Array = Golden.CASES
	if committed.size() != rows.size():
		same = false
	else:
		for i in rows.size():
			var mine: Dictionary = rows[i]
			var theirs: Dictionary = committed[i]
			same = same and JSON.stringify(mine["checks"]) == JSON.stringify(theirs["checks"]) and JSON.stringify(mine["final"]) == JSON.stringify(theirs["final"]) \
				and mine["seed"] == theirs["seed"] and mine["pace"] == theirs["pace"] and mine["years"] == theirs["years"]
	var file := FileAccess.open(out_path, FileAccess.WRITE)
	if file == null:
		return ["FAIL golden_gd: cannot write %s (error %d)" % [out_path, FileAccess.get_open_error()]]
	file.store_string(file_text(rows))
	file.close()
	lines.append("wrote %s (%s) in %.0f ms of simulation" % [out_path, ProjectSettings.globalize_path(out_path), total_ms])
	lines.append("the numbers %s the committed golden's (%s)" % ["equal" if same else "DIFFER from", Conformance.golden_source()])
	lines.append("GOLDEN_GD: %s" % ("written" if same else "written, and the rules have moved since the committed golden"))
	return lines
