// Writes the golden values the GDScript kernel must reproduce, from the JavaScript reference.
// Usage: node golden.mjs
//   -> game/scripts/studio/kernel/golden.gd   (hashes at every checkpoint, scenarios, chronicle hash)
//   -> chronicle-js.txt beside this file        (the full chronicle of one seed, for a line-by-line diff)
import { History, A, E, mix, hashWorld, line } from "./kernel.mjs";
import { writeFileSync } from "node:fs";

const YEARS = 500, EVERY = 25;
const SEEDS = Array.from({ length: 20 }, (_, i) => 1000 + i * 7919);
const CHRONICLE_SEED = 1000;

const checkpoints = {}, events = {}, settlements = {};
for (const seed of SEEDS) {
  const hist = new History(seed, [], EVERY);
  const w = hist.run(YEARS);
  const hashes = [];
  for (let y = 0; y < YEARS; y += EVERY) hashes.push(hashWorld(hist.checkpoints.get(y)));
  hashes.push(hashWorld(w));
  checkpoints[seed] = hashes;
  events[seed] = w.ev.year.length;
  settlements[seed] = w.n;
}

const act = (year, player, seq, kind, target, a = 0, b = 0) => ({ year, player, seq, kind, target, a, b });
const asRow = (x) => [x.year, x.player, x.seq, x.kind, x.target, x.a, x.b];
const scenarios = [];

// 1. Edit the past: warn a village of the flood that hit it.
{
  const w = new History(CHRONICLE_SEED).run(YEARS);
  let f = -1;
  for (let i = 0; i < w.ev.year.length; i++) if (w.ev.type[i] === E.FLOOD && w.ev.year[i] > 100 && w.ev.year[i] < 400) { f = i; break; }
  const actions = [act(w.ev.year[f] - 1, 1, 1, A.WARN, w.ev.sub[f], 3)];
  scenarios.push({ name: "warn-of-flood", seed: CHRONICLE_SEED, to: YEARS, actions, hash: hashWorld(new History(CHRONICLE_SEED, actions).run(YEARS)) });
}

// 2. Two players' logs, every kind of action, arriving in two different orders.
{
  const actions = [
    act(106, 1, 1, A.WARN, 2, 20), act(150, 1, 2, A.TEACH, 5, 9), act(200, 2, 1, A.GIFT, 7, 150),
    act(230, 2, 2, A.FELL, 1, 60), act(300, 1, 3, A.BRIDGE, 3), act(300, 2, 3, A.GIFT, 3, 40),
  ];
  const reversed = [...actions].reverse();
  const h1 = hashWorld(new History(CHRONICLE_SEED, actions).run(YEARS));
  const h2 = hashWorld(new History(CHRONICLE_SEED, reversed).run(YEARS));
  if (h1 !== h2) throw new Error("the reference itself is order-dependent");
  scenarios.push({ name: "two-players-merged", seed: CHRONICLE_SEED, to: YEARS, actions: reversed, hash: h1 });
}

// 3. A time storm folds 60% of the largest old village into year 350.
for (const seed of [SEEDS[2], SEEDS[11]]) {
  const hist = new History(seed);
  const w = hist.run(YEARS);
  const then = hist.stateAt(350);
  let origin = -1;
  for (let s = 0; s < w.n; s++) {
    if (w.pop[s] < 60 || s >= then.n || then.pop[s] <= 0) continue;
    if (origin < 0 || w.pop[s] > w.pop[origin]) origin = s;
  }
  const actions = [act(YEARS, 0, 1, A.STORM, origin, 600, 350)];
  scenarios.push({ name: `storm-${seed}`, seed, to: YEARS + 25, actions, hash: hashWorld(new History(seed, actions).run(YEARS + 25)) });
}

// The chronicle of one seed, as text, and a hash of its UTF-8 bytes.
const cw = new History(CHRONICLE_SEED).run(YEARS);
const lines = [];
for (let i = 0; i < cw.ev.year.length; i++) lines.push(`${String(cw.ev.year[i]).padStart(3)}  ${line(cw, i)}`);
const text = lines.join("\n") + "\n";
let ch = 2166136261;
for (const byte of Buffer.from(text, "utf8")) ch = mix((ch ^ byte) >>> 0);
const chronicleHash = ch.toString(16).padStart(8, "0");
writeFileSync(new URL("./chronicle-js.txt", import.meta.url), text);

// golden.gd
const q = (s) => JSON.stringify(s);
const g = [];
g.push("# Generated by tools-src/studio/kernel-reference/golden.mjs from the JavaScript reference. Do not edit.");
g.push("# The GDScript kernel must reproduce every value here (run.gd --conform).");
g.push("extends RefCounted");
g.push("");
g.push(`const YEARS := ${YEARS}`);
g.push(`const EVERY := ${EVERY}`);
g.push(`const SEEDS: Array[int] = [${SEEDS.join(", ")}]`);
g.push("# World hash at years 0, 25, ..., 500 for each seed.");
g.push("const CHECKPOINTS := {");
for (const seed of SEEDS) g.push(`\t${seed}: [${checkpoints[seed].map(q).join(", ")}],`);
g.push("}");
g.push(`const EVENTS := {${SEEDS.map((s) => `${s}: ${events[s]}`).join(", ")}}`);
g.push(`const SETTLEMENTS := {${SEEDS.map((s) => `${s}: ${settlements[s]}`).join(", ")}}`);
g.push("# actions: [year, player, seq, kind, target, a, b]");
g.push("const SCENARIOS := [");
for (const s of scenarios) g.push(`\t{"name": ${q(s.name)}, "seed": ${s.seed}, "to": ${s.to}, "actions": [${s.actions.map((x) => `[${asRow(x).join(", ")}]`).join(", ")}], "hash": ${q(s.hash)}},`);
g.push("]");
g.push(`const CHRONICLE_SEED := ${CHRONICLE_SEED}`);
g.push(`const CHRONICLE_LINES := ${lines.length}`);
g.push(`const CHRONICLE_HASH := ${q(chronicleHash)}`);
writeFileSync(new URL("../../../game/scripts/studio/kernel/golden.gd", import.meta.url), g.join("\n") + "\n");

console.log(`golden.gd written: ${SEEDS.length} seeds x ${YEARS / EVERY + 1} checkpoints, ${scenarios.length} scenarios, chronicle ${lines.length} lines (${chronicleHash})`);
for (const s of scenarios) console.log(`  ${s.name}: ${s.hash}  actions ${JSON.stringify(s.actions.map(asRow))}`);
console.log(`  seed ${SEEDS[0]} at year ${YEARS}: ${checkpoints[SEEDS[0]][YEARS / EVERY]}, ${settlements[SEEDS[0]]} settlements, ${events[SEEDS[0]]} events`);
